// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file terra/dyncomm/v1beta1/query.proto (package terra.dyncomm.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryParamsRequest, QueryParamsResponse, QueryRateRequest, QueryRateResponse } from "./query_pb.js";

const TYPE_NAME = "terra.dyncomm.v1beta1.Query";

/**
 * Params queries all parameters.
 *
 * @generated from rpc terra.dyncomm.v1beta1.Query.Params
 */
export const QueryParamsService = {
  typeName: TYPE_NAME,
  method: "Params",
  Request: QueryParamsRequest,
  Response: QueryParamsResponse,
} as const;

/**
 * @generated from rpc terra.dyncomm.v1beta1.Query.Rate
 */
export const QueryRateService = {
  typeName: TYPE_NAME,
  method: "Rate",
  Request: QueryRateRequest,
  Response: QueryRateResponse,
} as const;

