// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file terra/wasm/v1beta1/wasm.proto (package terra.wasm.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * CodeInfo is data for the uploaded contract WASM code
 *
 * @generated from message terra.wasm.v1beta1.LegacyCodeInfo
 */
export class LegacyCodeInfo extends Message<LegacyCodeInfo> {
  /**
   * CodeID is the sequentially increasing unique identifier
   *
   * @generated from field: uint64 code_id = 1;
   */
  codeId = protoInt64.zero;

  /**
   * CodeHash is the unique identifier created by wasmvm
   *
   * @generated from field: bytes code_hash = 2;
   */
  codeHash = new Uint8Array(0);

  /**
   * Creator address who initially stored the code
   *
   * @generated from field: string creator = 3;
   */
  creator = "";

  constructor(data?: PartialMessage<LegacyCodeInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.wasm.v1beta1.LegacyCodeInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "code_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "code_hash", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 3, name: "creator", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LegacyCodeInfo {
    return new LegacyCodeInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LegacyCodeInfo {
    return new LegacyCodeInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LegacyCodeInfo {
    return new LegacyCodeInfo().fromJsonString(jsonString, options);
  }

  static equals(a: LegacyCodeInfo | PlainMessage<LegacyCodeInfo> | undefined, b: LegacyCodeInfo | PlainMessage<LegacyCodeInfo> | undefined): boolean {
    return proto3.util.equals(LegacyCodeInfo, a, b);
  }
}

/**
 * ContractInfo stores a WASM contract instance
 *
 * @generated from message terra.wasm.v1beta1.LegacyContractInfo
 */
export class LegacyContractInfo extends Message<LegacyContractInfo> {
  /**
   * Address is the address of the contract
   *
   * @generated from field: string address = 1;
   */
  address = "";

  /**
   * Creator is the contract creator address
   *
   * @generated from field: string creator = 2;
   */
  creator = "";

  /**
   * Admin is who can execute the contract migration
   *
   * @generated from field: string admin = 3;
   */
  admin = "";

  /**
   * CodeID is the reference to the stored Wasm code
   *
   * @generated from field: uint64 code_id = 4;
   */
  codeId = protoInt64.zero;

  /**
   * InitMsg is the raw message used when instantiating a contract
   *
   * @generated from field: bytes init_msg = 5;
   */
  initMsg = new Uint8Array(0);

  constructor(data?: PartialMessage<LegacyContractInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.wasm.v1beta1.LegacyContractInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "creator", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "admin", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "code_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 5, name: "init_msg", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LegacyContractInfo {
    return new LegacyContractInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LegacyContractInfo {
    return new LegacyContractInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LegacyContractInfo {
    return new LegacyContractInfo().fromJsonString(jsonString, options);
  }

  static equals(a: LegacyContractInfo | PlainMessage<LegacyContractInfo> | undefined, b: LegacyContractInfo | PlainMessage<LegacyContractInfo> | undefined): boolean {
    return proto3.util.equals(LegacyContractInfo, a, b);
  }
}

