// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file vsc/feedistribute/v1/query.proto (package vsc.feedistribute.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryFeeSharesRequest, QueryFeeSharesResponse } from "./query_pb.js";

const TYPE_NAME = "vsc.feedistribute.v1.Query";

/**
 * ExchangeRate returns exchange rate of a pair
 *
 * @generated from rpc vsc.feedistribute.v1.Query.FeeShares
 */
export const QueryFeeSharesService = {
  typeName: TYPE_NAME,
  method: "FeeShares",
  Request: QueryFeeSharesRequest,
  Response: QueryFeeSharesResponse,
} as const;

