// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file vsc/feedistribute/v1/tx.proto (package vsc.feedistribute.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgFeeDistributeShares, MsgFeeDistributeSharesResponse } from "./tx_pb.js";

const TYPE_NAME = "vsc.feedistribute.v1.Msg";

/**
 * AggregateExchangeRatePrevote defines a method for submitting
 * aggregate exchange rate prevote
 *
 * @generated from rpc vsc.feedistribute.v1.Msg.FeeDistributeShares
 */
export const MsgFeeDistributeSharesService = {
  typeName: TYPE_NAME,
  method: "FeeDistributeShares",
  Request: MsgFeeDistributeShares,
  Response: MsgFeeDistributeSharesResponse,
} as const;

