// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file terra/vesting/v1beta1/vesting.proto (package terra.vesting.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { BaseVestingAccount } from "cosmes/protobufs/sdk47/cosmos/vesting/v1beta1/vesting_pb.js";

/**
 * LazyGradedVestingAccount implements the LazyGradedVestingAccount interface. It vests all
 * coins according to a predefined schedule.
 *
 * @generated from message terra.vesting.v1beta1.LazyGradedVestingAccount
 */
export class LazyGradedVestingAccount extends Message<LazyGradedVestingAccount> {
  /**
   * @generated from field: cosmos.vesting.v1beta1.BaseVestingAccount base_vesting_account = 1;
   */
  baseVestingAccount?: BaseVestingAccount;

  /**
   * @generated from field: repeated terra.vesting.v1beta1.VestingSchedule vesting_schedules = 2;
   */
  vestingSchedules: VestingSchedule[] = [];

  constructor(data?: PartialMessage<LazyGradedVestingAccount>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.vesting.v1beta1.LazyGradedVestingAccount";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "base_vesting_account", kind: "message", T: BaseVestingAccount },
    { no: 2, name: "vesting_schedules", kind: "message", T: VestingSchedule, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LazyGradedVestingAccount {
    return new LazyGradedVestingAccount().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LazyGradedVestingAccount {
    return new LazyGradedVestingAccount().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LazyGradedVestingAccount {
    return new LazyGradedVestingAccount().fromJsonString(jsonString, options);
  }

  static equals(a: LazyGradedVestingAccount | PlainMessage<LazyGradedVestingAccount> | undefined, b: LazyGradedVestingAccount | PlainMessage<LazyGradedVestingAccount> | undefined): boolean {
    return proto3.util.equals(LazyGradedVestingAccount, a, b);
  }
}

/**
 * Schedule - represent single schedule data for a vesting schedule
 *
 * @generated from message terra.vesting.v1beta1.Schedule
 */
export class Schedule extends Message<Schedule> {
  /**
   * @generated from field: int64 start_time = 1;
   */
  startTime = protoInt64.zero;

  /**
   * @generated from field: int64 end_time = 2;
   */
  endTime = protoInt64.zero;

  /**
   * @generated from field: string ratio = 3;
   */
  ratio = "";

  constructor(data?: PartialMessage<Schedule>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.vesting.v1beta1.Schedule";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "start_time", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "end_time", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "ratio", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Schedule {
    return new Schedule().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Schedule {
    return new Schedule().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Schedule {
    return new Schedule().fromJsonString(jsonString, options);
  }

  static equals(a: Schedule | PlainMessage<Schedule> | undefined, b: Schedule | PlainMessage<Schedule> | undefined): boolean {
    return proto3.util.equals(Schedule, a, b);
  }
}

/**
 * VestingSchedule defines vesting schedule for a denom
 *
 * @generated from message terra.vesting.v1beta1.VestingSchedule
 */
export class VestingSchedule extends Message<VestingSchedule> {
  /**
   * @generated from field: string denom = 1;
   */
  denom = "";

  /**
   * @generated from field: repeated terra.vesting.v1beta1.Schedule schedules = 2;
   */
  schedules: Schedule[] = [];

  constructor(data?: PartialMessage<VestingSchedule>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.vesting.v1beta1.VestingSchedule";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "denom", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "schedules", kind: "message", T: Schedule, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VestingSchedule {
    return new VestingSchedule().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VestingSchedule {
    return new VestingSchedule().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VestingSchedule {
    return new VestingSchedule().fromJsonString(jsonString, options);
  }

  static equals(a: VestingSchedule | PlainMessage<VestingSchedule> | undefined, b: VestingSchedule | PlainMessage<VestingSchedule> | undefined): boolean {
    return proto3.util.equals(VestingSchedule, a, b);
  }
}

