// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file terra/tx/v1beta1/service.proto (package terra.tx.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ComputeTaxRequest, ComputeTaxResponse } from "./service_pb.js";

const TYPE_NAME = "terra.tx.v1beta1.Service";

/**
 * EstimateFee simulates executing a transaction for estimating gas usage.
 *
 * @generated from rpc terra.tx.v1beta1.Service.ComputeTax
 */
export const ServiceComputeTaxService = {
  typeName: TYPE_NAME,
  method: "ComputeTax",
  Request: ComputeTaxRequest,
  Response: ComputeTaxResponse,
} as const;

