// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file terra/tx/v1beta1/service.proto (package terra.tx.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Tx } from "cosmes/protobufs/sdk47/cosmos/tx/v1beta1/tx_pb.js";
import { Coin } from "cosmes/protobufs/sdk47/cosmos/base/v1beta1/coin_pb.js";

/**
 * ComputeTaxRequest is the request type for the Service.ComputeTax
 * RPC method.
 *
 * @generated from message terra.tx.v1beta1.ComputeTaxRequest
 */
export class ComputeTaxRequest extends Message<ComputeTaxRequest> {
  /**
   * tx is the transaction to simulate.
   * Deprecated. Send raw tx bytes instead.
   *
   * @generated from field: cosmos.tx.v1beta1.Tx tx = 1 [deprecated = true];
   * @deprecated
   */
  tx?: Tx;

  /**
   * tx_bytes is the raw transaction.
   *
   * @generated from field: bytes tx_bytes = 2;
   */
  txBytes = new Uint8Array(0);

  constructor(data?: PartialMessage<ComputeTaxRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.tx.v1beta1.ComputeTaxRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "tx", kind: "message", T: Tx },
    { no: 2, name: "tx_bytes", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ComputeTaxRequest {
    return new ComputeTaxRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ComputeTaxRequest {
    return new ComputeTaxRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ComputeTaxRequest {
    return new ComputeTaxRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ComputeTaxRequest | PlainMessage<ComputeTaxRequest> | undefined, b: ComputeTaxRequest | PlainMessage<ComputeTaxRequest> | undefined): boolean {
    return proto3.util.equals(ComputeTaxRequest, a, b);
  }
}

/**
 * ComputeTaxResponse is the response type for the Service.ComputeTax
 * RPC method.
 *
 * @generated from message terra.tx.v1beta1.ComputeTaxResponse
 */
export class ComputeTaxResponse extends Message<ComputeTaxResponse> {
  /**
   * amount is the amount of coins to be paid as a fee
   *
   * @generated from field: repeated cosmos.base.v1beta1.Coin tax_amount = 1;
   */
  taxAmount: Coin[] = [];

  constructor(data?: PartialMessage<ComputeTaxResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.tx.v1beta1.ComputeTaxResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "tax_amount", kind: "message", T: Coin, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ComputeTaxResponse {
    return new ComputeTaxResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ComputeTaxResponse {
    return new ComputeTaxResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ComputeTaxResponse {
    return new ComputeTaxResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ComputeTaxResponse | PlainMessage<ComputeTaxResponse> | undefined, b: ComputeTaxResponse | PlainMessage<ComputeTaxResponse> | undefined): boolean {
    return proto3.util.equals(ComputeTaxResponse, a, b);
  }
}

