// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file terra/taxexemption/v1/taxexemption.proto (package terra.taxexemption.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message terra.taxexemption.v1.Zone
 */
export class Zone extends Message<Zone> {
  /**
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * @generated from field: bool outgoing = 2;
   */
  outgoing = false;

  /**
   * @generated from field: bool incoming = 3;
   */
  incoming = false;

  /**
   * @generated from field: bool cross_zone = 4;
   */
  crossZone = false;

  constructor(data?: PartialMessage<Zone>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.taxexemption.v1.Zone";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "outgoing", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "incoming", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "cross_zone", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Zone {
    return new Zone().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Zone {
    return new Zone().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Zone {
    return new Zone().fromJsonString(jsonString, options);
  }

  static equals(a: Zone | PlainMessage<Zone> | undefined, b: Zone | PlainMessage<Zone> | undefined): boolean {
    return proto3.util.equals(Zone, a, b);
  }
}

/**
 * @generated from message terra.taxexemption.v1.ZoneList
 */
export class ZoneList extends Message<ZoneList> {
  /**
   * @generated from field: repeated string zones = 1;
   */
  zones: string[] = [];

  constructor(data?: PartialMessage<ZoneList>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.taxexemption.v1.ZoneList";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "zones", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ZoneList {
    return new ZoneList().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ZoneList {
    return new ZoneList().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ZoneList {
    return new ZoneList().fromJsonString(jsonString, options);
  }

  static equals(a: ZoneList | PlainMessage<ZoneList> | undefined, b: ZoneList | PlainMessage<ZoneList> | undefined): boolean {
    return proto3.util.equals(ZoneList, a, b);
  }
}

/**
 * @generated from message terra.taxexemption.v1.ProposalMetadata
 */
export class ProposalMetadata extends Message<ProposalMetadata> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string forum = 3;
   */
  forum = "";

  /**
   * @generated from field: string other = 4;
   */
  other = "";

  constructor(data?: PartialMessage<ProposalMetadata>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.taxexemption.v1.ProposalMetadata";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "forum", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "other", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ProposalMetadata {
    return new ProposalMetadata().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ProposalMetadata {
    return new ProposalMetadata().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ProposalMetadata {
    return new ProposalMetadata().fromJsonString(jsonString, options);
  }

  static equals(a: ProposalMetadata | PlainMessage<ProposalMetadata> | undefined, b: ProposalMetadata | PlainMessage<ProposalMetadata> | undefined): boolean {
    return proto3.util.equals(ProposalMetadata, a, b);
  }
}

/**
 * @generated from message terra.taxexemption.v1.AddTaxExemptionZoneProposal
 */
export class AddTaxExemptionZoneProposal extends Message<AddTaxExemptionZoneProposal> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string zone = 3;
   */
  zone = "";

  /**
   * @generated from field: bool outgoing = 4;
   */
  outgoing = false;

  /**
   * @generated from field: bool incoming = 5;
   */
  incoming = false;

  /**
   * @generated from field: bool cross_zone = 6;
   */
  crossZone = false;

  /**
   * @generated from field: repeated string addresses = 7;
   */
  addresses: string[] = [];

  /**
   * @generated from field: string authority = 8;
   */
  authority = "";

  constructor(data?: PartialMessage<AddTaxExemptionZoneProposal>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.taxexemption.v1.AddTaxExemptionZoneProposal";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "zone", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "outgoing", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "incoming", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "cross_zone", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 7, name: "addresses", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 8, name: "authority", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AddTaxExemptionZoneProposal {
    return new AddTaxExemptionZoneProposal().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AddTaxExemptionZoneProposal {
    return new AddTaxExemptionZoneProposal().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AddTaxExemptionZoneProposal {
    return new AddTaxExemptionZoneProposal().fromJsonString(jsonString, options);
  }

  static equals(a: AddTaxExemptionZoneProposal | PlainMessage<AddTaxExemptionZoneProposal> | undefined, b: AddTaxExemptionZoneProposal | PlainMessage<AddTaxExemptionZoneProposal> | undefined): boolean {
    return proto3.util.equals(AddTaxExemptionZoneProposal, a, b);
  }
}

/**
 * @generated from message terra.taxexemption.v1.RemoveTaxExemptionZoneProposal
 */
export class RemoveTaxExemptionZoneProposal extends Message<RemoveTaxExemptionZoneProposal> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string zone = 3;
   */
  zone = "";

  /**
   * @generated from field: string authority = 4;
   */
  authority = "";

  constructor(data?: PartialMessage<RemoveTaxExemptionZoneProposal>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.taxexemption.v1.RemoveTaxExemptionZoneProposal";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "zone", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "authority", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RemoveTaxExemptionZoneProposal {
    return new RemoveTaxExemptionZoneProposal().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RemoveTaxExemptionZoneProposal {
    return new RemoveTaxExemptionZoneProposal().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RemoveTaxExemptionZoneProposal {
    return new RemoveTaxExemptionZoneProposal().fromJsonString(jsonString, options);
  }

  static equals(a: RemoveTaxExemptionZoneProposal | PlainMessage<RemoveTaxExemptionZoneProposal> | undefined, b: RemoveTaxExemptionZoneProposal | PlainMessage<RemoveTaxExemptionZoneProposal> | undefined): boolean {
    return proto3.util.equals(RemoveTaxExemptionZoneProposal, a, b);
  }
}

/**
 * @generated from message terra.taxexemption.v1.ModifyTaxExemptionZoneProposal
 */
export class ModifyTaxExemptionZoneProposal extends Message<ModifyTaxExemptionZoneProposal> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string zone = 3;
   */
  zone = "";

  /**
   * @generated from field: bool outgoing = 4;
   */
  outgoing = false;

  /**
   * @generated from field: bool incoming = 5;
   */
  incoming = false;

  /**
   * @generated from field: bool cross_zone = 6;
   */
  crossZone = false;

  /**
   * @generated from field: string authority = 7;
   */
  authority = "";

  constructor(data?: PartialMessage<ModifyTaxExemptionZoneProposal>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.taxexemption.v1.ModifyTaxExemptionZoneProposal";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "zone", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "outgoing", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "incoming", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "cross_zone", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 7, name: "authority", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ModifyTaxExemptionZoneProposal {
    return new ModifyTaxExemptionZoneProposal().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ModifyTaxExemptionZoneProposal {
    return new ModifyTaxExemptionZoneProposal().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ModifyTaxExemptionZoneProposal {
    return new ModifyTaxExemptionZoneProposal().fromJsonString(jsonString, options);
  }

  static equals(a: ModifyTaxExemptionZoneProposal | PlainMessage<ModifyTaxExemptionZoneProposal> | undefined, b: ModifyTaxExemptionZoneProposal | PlainMessage<ModifyTaxExemptionZoneProposal> | undefined): boolean {
    return proto3.util.equals(ModifyTaxExemptionZoneProposal, a, b);
  }
}

/**
 * @generated from message terra.taxexemption.v1.AddTaxExemptionAddressProposal
 */
export class AddTaxExemptionAddressProposal extends Message<AddTaxExemptionAddressProposal> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string zone = 3;
   */
  zone = "";

  /**
   * @generated from field: repeated string addresses = 4;
   */
  addresses: string[] = [];

  /**
   * @generated from field: string authority = 5;
   */
  authority = "";

  constructor(data?: PartialMessage<AddTaxExemptionAddressProposal>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.taxexemption.v1.AddTaxExemptionAddressProposal";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "zone", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "addresses", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 5, name: "authority", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AddTaxExemptionAddressProposal {
    return new AddTaxExemptionAddressProposal().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AddTaxExemptionAddressProposal {
    return new AddTaxExemptionAddressProposal().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AddTaxExemptionAddressProposal {
    return new AddTaxExemptionAddressProposal().fromJsonString(jsonString, options);
  }

  static equals(a: AddTaxExemptionAddressProposal | PlainMessage<AddTaxExemptionAddressProposal> | undefined, b: AddTaxExemptionAddressProposal | PlainMessage<AddTaxExemptionAddressProposal> | undefined): boolean {
    return proto3.util.equals(AddTaxExemptionAddressProposal, a, b);
  }
}

/**
 * @generated from message terra.taxexemption.v1.RemoveTaxExemptionAddressProposal
 */
export class RemoveTaxExemptionAddressProposal extends Message<RemoveTaxExemptionAddressProposal> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string zone = 3;
   */
  zone = "";

  /**
   * @generated from field: repeated string addresses = 4;
   */
  addresses: string[] = [];

  /**
   * @generated from field: string authority = 5;
   */
  authority = "";

  constructor(data?: PartialMessage<RemoveTaxExemptionAddressProposal>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.taxexemption.v1.RemoveTaxExemptionAddressProposal";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "zone", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "addresses", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 5, name: "authority", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RemoveTaxExemptionAddressProposal {
    return new RemoveTaxExemptionAddressProposal().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RemoveTaxExemptionAddressProposal {
    return new RemoveTaxExemptionAddressProposal().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RemoveTaxExemptionAddressProposal {
    return new RemoveTaxExemptionAddressProposal().fromJsonString(jsonString, options);
  }

  static equals(a: RemoveTaxExemptionAddressProposal | PlainMessage<RemoveTaxExemptionAddressProposal> | undefined, b: RemoveTaxExemptionAddressProposal | PlainMessage<RemoveTaxExemptionAddressProposal> | undefined): boolean {
    return proto3.util.equals(RemoveTaxExemptionAddressProposal, a, b);
  }
}

