// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file terra/taxexemption/v1/tx.proto (package terra.taxexemption.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgAddTaxExemptionAddress, MsgAddTaxExemptionAddressResponse, MsgAddTaxExemptionZone, MsgAddTaxExemptionZoneResponse, MsgModifyTaxExemptionZone, MsgModifyTaxExemptionZoneResponse, MsgRemoveTaxExemptionAddress, MsgRemoveTaxExemptionAddressResponse, MsgRemoveTaxExemptionZone, MsgRemoveTaxExemptionZoneResponse } from "./tx_pb.js";

const TYPE_NAME = "terra.taxexemption.v1.Msg";

/**
 * @generated from rpc terra.taxexemption.v1.Msg.AddTaxExemptionZone
 */
export const MsgAddTaxExemptionZoneService = {
  typeName: TYPE_NAME,
  method: "AddTaxExemptionZone",
  Request: MsgAddTaxExemptionZone,
  Response: MsgAddTaxExemptionZoneResponse,
} as const;

/**
 * @generated from rpc terra.taxexemption.v1.Msg.RemoveTaxExemptionZone
 */
export const MsgRemoveTaxExemptionZoneService = {
  typeName: TYPE_NAME,
  method: "RemoveTaxExemptionZone",
  Request: MsgRemoveTaxExemptionZone,
  Response: MsgRemoveTaxExemptionZoneResponse,
} as const;

/**
 * @generated from rpc terra.taxexemption.v1.Msg.ModifyTaxExemptionZone
 */
export const MsgModifyTaxExemptionZoneService = {
  typeName: TYPE_NAME,
  method: "ModifyTaxExemptionZone",
  Request: MsgModifyTaxExemptionZone,
  Response: MsgModifyTaxExemptionZoneResponse,
} as const;

/**
 * @generated from rpc terra.taxexemption.v1.Msg.AddTaxExemptionAddress
 */
export const MsgAddTaxExemptionAddressService = {
  typeName: TYPE_NAME,
  method: "AddTaxExemptionAddress",
  Request: MsgAddTaxExemptionAddress,
  Response: MsgAddTaxExemptionAddressResponse,
} as const;

/**
 * @generated from rpc terra.taxexemption.v1.Msg.RemoveTaxExemptionAddress
 */
export const MsgRemoveTaxExemptionAddressService = {
  typeName: TYPE_NAME,
  method: "RemoveTaxExemptionAddress",
  Request: MsgRemoveTaxExemptionAddress,
  Response: MsgRemoveTaxExemptionAddressResponse,
} as const;

