// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file vsc/erc20/v1/tx.proto (package vsc.erc20.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgBurnCoins, MsgBurnCoinsResponse, MsgMintCoins, MsgMintCoinsResponse, MsgRegisterCoin, MsgRegisterCoinResponse, MsgUpdateParams, MsgUpdateParamsResponse } from "./tx_pb.js";

const TYPE_NAME = "vsc.erc20.v1.Msg";

/**
 * @generated from rpc vsc.erc20.v1.Msg.RegisterCoin
 */
export const MsgRegisterCoinService = {
  typeName: TYPE_NAME,
  method: "RegisterCoin",
  Request: MsgRegisterCoin,
  Response: MsgRegisterCoinResponse,
} as const;

/**
 * @generated from rpc vsc.erc20.v1.Msg.UpdateParams
 */
export const MsgUpdateParamsService = {
  typeName: TYPE_NAME,
  method: "UpdateParams",
  Request: MsgUpdateParams,
  Response: MsgUpdateParamsResponse,
} as const;

/**
 * @generated from rpc vsc.erc20.v1.Msg.MintCoins
 */
export const MsgMintCoinsService = {
  typeName: TYPE_NAME,
  method: "MintCoins",
  Request: MsgMintCoins,
  Response: MsgMintCoinsResponse,
} as const;

/**
 * @generated from rpc vsc.erc20.v1.Msg.BurnCoins
 */
export const MsgBurnCoinsService = {
  typeName: TYPE_NAME,
  method: "BurnCoins",
  Request: MsgBurnCoins,
  Response: MsgBurnCoinsResponse,
} as const;

