// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file vsc/permissions/v1/query.proto (package vsc.permissions.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryAllPermissionsRequest, QueryAllPermissionsResponse, QueryPermissionRequest, QueryPermissionResponse } from "./query_pb.js";

const TYPE_NAME = "vsc.permissions.v1.Query";

/**
 * Permission queries a permission by name.
 *
 * @generated from rpc vsc.permissions.v1.Query.Permission
 */
export const QueryPermissionService = {
  typeName: TYPE_NAME,
  method: "Permission",
  Request: QueryPermissionRequest,
  Response: QueryPermissionResponse,
} as const;

/**
 * AllPermissions queries all permissions.
 *
 * @generated from rpc vsc.permissions.v1.Query.AllPermissions
 */
export const QueryAllPermissionsService = {
  typeName: TYPE_NAME,
  method: "AllPermissions",
  Request: QueryAllPermissionsRequest,
  Response: QueryAllPermissionsResponse,
} as const;

