// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file vsc/permissions/v1/tx.proto (package vsc.permissions.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgUpdatePermissions, MsgUpdatePermissionsResponse } from "./tx_pb.js";

const TYPE_NAME = "vsc.permissions.v1.Msg";

/**
 * @generated from rpc vsc.permissions.v1.Msg.UpdatePermissions
 */
export const MsgUpdatePermissionsService = {
  typeName: TYPE_NAME,
  method: "UpdatePermissions",
  Request: MsgUpdatePermissions,
  Response: MsgUpdatePermissionsResponse,
} as const;

