// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file ibc/applications/gmp/v1/genesis.proto (package ibc.applications.gmp.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { AccountIdentifier } from "cosmes/protobufs/sdk47/ibc/applications/gmp/v1/account_pb.js";

/**
 * GenesisState defines the 27-gmp genesis state
 *
 * @generated from message ibc.applications.gmp.v1.GenesisState
 */
export class GenesisState extends Message<GenesisState> {
  /**
   * The list of registered ICS27 accounts
   *
   * @generated from field: repeated ibc.applications.gmp.v1.RegisteredICS27Account ics27_accounts = 2;
   */
  ics27Accounts: RegisteredICS27Account[] = [];

  constructor(data?: PartialMessage<GenesisState>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ibc.applications.gmp.v1.GenesisState";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "ics27_accounts", kind: "message", T: RegisteredICS27Account, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GenesisState {
    return new GenesisState().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GenesisState {
    return new GenesisState().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GenesisState {
    return new GenesisState().fromJsonString(jsonString, options);
  }

  static equals(a: GenesisState | PlainMessage<GenesisState> | undefined, b: GenesisState | PlainMessage<GenesisState> | undefined): boolean {
    return proto3.util.equals(GenesisState, a, b);
  }
}

/**
 * RegisteredICS27Account contains an account identifier and associated interchain account address
 *
 * @generated from message ibc.applications.gmp.v1.RegisteredICS27Account
 */
export class RegisteredICS27Account extends Message<RegisteredICS27Account> {
  /**
   * / The address of the ics27 account
   *
   * @generated from field: string account_address = 1;
   */
  accountAddress = "";

  /**
   * / The account identifier
   *
   * @generated from field: ibc.applications.gmp.v1.AccountIdentifier account_id = 2;
   */
  accountId?: AccountIdentifier;

  constructor(data?: PartialMessage<RegisteredICS27Account>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ibc.applications.gmp.v1.RegisteredICS27Account";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "account_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "account_id", kind: "message", T: AccountIdentifier },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RegisteredICS27Account {
    return new RegisteredICS27Account().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RegisteredICS27Account {
    return new RegisteredICS27Account().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RegisteredICS27Account {
    return new RegisteredICS27Account().fromJsonString(jsonString, options);
  }

  static equals(a: RegisteredICS27Account | PlainMessage<RegisteredICS27Account> | undefined, b: RegisteredICS27Account | PlainMessage<RegisteredICS27Account> | undefined): boolean {
    return proto3.util.equals(RegisteredICS27Account, a, b);
  }
}

