// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file ibc/applications/gmp/v1/packet.proto (package ibc.applications.gmp.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * GMPPacketData defines a struct for the packet payload
 *
 * @generated from message ibc.applications.gmp.v1.GMPPacketData
 */
export class GMPPacketData extends Message<GMPPacketData> {
  /**
   * the sender address
   *
   * @generated from field: string sender = 1;
   */
  sender = "";

  /**
   * the recipient address on the destination chain
   *
   * @generated from field: string receiver = 2;
   */
  receiver = "";

  /**
   * The salt used to generate the caller account address
   *
   * @generated from field: bytes salt = 3;
   */
  salt = new Uint8Array(0);

  /**
   * The payload of the call
   *
   * @generated from field: bytes payload = 4;
   */
  payload = new Uint8Array(0);

  /**
   * optional memo
   *
   * @generated from field: string memo = 5;
   */
  memo = "";

  constructor(data?: PartialMessage<GMPPacketData>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ibc.applications.gmp.v1.GMPPacketData";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "sender", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "receiver", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "salt", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 4, name: "payload", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 5, name: "memo", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GMPPacketData {
    return new GMPPacketData().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GMPPacketData {
    return new GMPPacketData().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GMPPacketData {
    return new GMPPacketData().fromJsonString(jsonString, options);
  }

  static equals(a: GMPPacketData | PlainMessage<GMPPacketData> | undefined, b: GMPPacketData | PlainMessage<GMPPacketData> | undefined): boolean {
    return proto3.util.equals(GMPPacketData, a, b);
  }
}

/**
 * Acknowledgement defines a struct for the ICS27-2 acknowledgement
 *
 * @generated from message ibc.applications.gmp.v1.Acknowledgement
 */
export class Acknowledgement extends Message<Acknowledgement> {
  /**
   * The result of the call
   *
   * @generated from field: bytes result = 1;
   */
  result = new Uint8Array(0);

  constructor(data?: PartialMessage<Acknowledgement>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ibc.applications.gmp.v1.Acknowledgement";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "result", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Acknowledgement {
    return new Acknowledgement().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Acknowledgement {
    return new Acknowledgement().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Acknowledgement {
    return new Acknowledgement().fromJsonString(jsonString, options);
  }

  static equals(a: Acknowledgement | PlainMessage<Acknowledgement> | undefined, b: Acknowledgement | PlainMessage<Acknowledgement> | undefined): boolean {
    return proto3.util.equals(Acknowledgement, a, b);
  }
}

