// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file ibc/applications/gmp/v1/query.proto (package ibc.applications.gmp.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryAccountAddressRequest, QueryAccountAddressResponse, QueryAccountIdentifierRequest, QueryAccountIdentifierResponse } from "./query_pb.js";

const TYPE_NAME = "ibc.applications.gmp.v1.Query";

/**
 * AccountAddress queries the interchain account address for a given client_id, sender, and salt.
 * If the account is not registered, the address is computed deterministically
 *
 * @generated from rpc ibc.applications.gmp.v1.Query.AccountAddress
 */
export const QueryAccountAddressService = {
  typeName: TYPE_NAME,
  method: "AccountAddress",
  Request: QueryAccountAddressRequest,
  Response: QueryAccountAddressResponse,
} as const;

/**
 * AccountIdentifier queries the account identifier for a given interchain account address.
 *
 * @generated from rpc ibc.applications.gmp.v1.Query.AccountIdentifier
 */
export const QueryAccountIdentifierService = {
  typeName: TYPE_NAME,
  method: "AccountIdentifier",
  Request: QueryAccountIdentifierRequest,
  Response: QueryAccountIdentifierResponse,
} as const;

