// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file ibc/applications/gmp/v1/tx.proto (package ibc.applications.gmp.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgSendCall, MsgSendCallResponse } from "./tx_pb.js";

const TYPE_NAME = "ibc.applications.gmp.v1.Msg";

/**
 * SendCall defines a rpc handler method for MsgSendCall.
 *
 * @generated from rpc ibc.applications.gmp.v1.Msg.SendCall
 */
export const MsgSendCallService = {
  typeName: TYPE_NAME,
  method: "SendCall",
  Request: MsgSendCall,
  Response: MsgSendCallResponse,
} as const;

