// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file vsc/erc20/v1/erc20.proto (package vsc.erc20.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * Owner enumerates the ownership of a ERC20 contract.
 *
 * @generated from enum vsc.erc20.v1.Owner
 */
export enum Owner {
  /**
   * OWNER_UNSPECIFIED defines an invalid/undefined owner.
   *
   * @generated from enum value: OWNER_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * OWNER_MODULE - erc20 is owned by the erc20 module account.
   *
   * @generated from enum value: OWNER_MODULE = 1;
   */
  MODULE = 1,

  /**
   * OWNER_EXTERNAL - erc20 is owned by an external account.
   *
   * @generated from enum value: OWNER_EXTERNAL = 2;
   */
  EXTERNAL = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(Owner)
proto3.util.setEnumType(Owner, "vsc.erc20.v1.Owner", [
  { no: 0, name: "OWNER_UNSPECIFIED" },
  { no: 1, name: "OWNER_MODULE" },
  { no: 2, name: "OWNER_EXTERNAL" },
]);

/**
 * TokenPair defines an instance that records a pairing consisting of a native
 *  Cosmos Coin and an ERC20 token address.
 *
 * @generated from message vsc.erc20.v1.TokenPair
 */
export class TokenPair extends Message<TokenPair> {
  /**
   * erc20_address is the hex address of ERC20 contract token
   *
   * @generated from field: string erc20_address = 1;
   */
  erc20Address = "";

  /**
   * denom defines the cosmos base denomination to be mapped to
   *
   * @generated from field: string denom = 2;
   */
  denom = "";

  /**
   * enabled defines the token mapping enable status
   *
   * @generated from field: bool enabled = 3;
   */
  enabled = false;

  /**
   * contract_owner is the an ENUM specifying the type of ERC20 owner (0
   * invalid, 1 ModuleAccount, 2 external address)
   *
   * @generated from field: vsc.erc20.v1.Owner contract_owner = 4;
   */
  contractOwner = Owner.UNSPECIFIED;

  constructor(data?: PartialMessage<TokenPair>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "vsc.erc20.v1.TokenPair";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "erc20_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "denom", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "contract_owner", kind: "enum", T: proto3.getEnumType(Owner) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TokenPair {
    return new TokenPair().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TokenPair {
    return new TokenPair().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TokenPair {
    return new TokenPair().fromJsonString(jsonString, options);
  }

  static equals(a: TokenPair | PlainMessage<TokenPair> | undefined, b: TokenPair | PlainMessage<TokenPair> | undefined): boolean {
    return proto3.util.equals(TokenPair, a, b);
  }
}

