// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file vsc/erc20/v1/query.proto (package vsc.erc20.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryParamsRequest, QueryParamsResponse, QueryTokenPairRequest, QueryTokenPairResponse, QueryTokenPairsRequest, QueryTokenPairsResponse } from "./query_pb.js";

const TYPE_NAME = "vsc.erc20.v1.Query";

/**
 * TokenPairs retrieves registered token pairs
 *
 * @generated from rpc vsc.erc20.v1.Query.TokenPairs
 */
export const QueryTokenPairsService = {
  typeName: TYPE_NAME,
  method: "TokenPairs",
  Request: QueryTokenPairsRequest,
  Response: QueryTokenPairsResponse,
} as const;

/**
 * TokenPair retrieves a registered token pair
 *
 * @generated from rpc vsc.erc20.v1.Query.TokenPair
 */
export const QueryTokenPairService = {
  typeName: TYPE_NAME,
  method: "TokenPair",
  Request: QueryTokenPairRequest,
  Response: QueryTokenPairResponse,
} as const;

/**
 * Params retrieves the erc20 module params
 *
 * @generated from rpc vsc.erc20.v1.Query.Params
 */
export const QueryParamsService = {
  typeName: TYPE_NAME,
  method: "Params",
  Request: QueryParamsRequest,
  Response: QueryParamsResponse,
} as const;

