// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file vsc/erc20/v1/tx.proto (package vsc.erc20.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Metadata } from "cosmes/protobufs/sdk47/cosmos/bank/v1beta1/bank_pb.js";
import { TokenPair } from "cosmes/protobufs/sdk47/vsc/erc20/v1/erc20_pb.js";
import { Params } from "cosmes/protobufs/sdk47/vsc/erc20/v1/genesis_pb.js";
import { Coin } from "cosmes/protobufs/sdk47/cosmos/base/v1beta1/coin_pb.js";

/**
 * MsgRegisterCoin defines a permissioned Msg to create a new token pair.
 * which is a mapping between a denom <-> erc20_address.
 *
 * @generated from message vsc.erc20.v1.MsgRegisterCoin
 */
export class MsgRegisterCoin extends Message<MsgRegisterCoin> {
  /**
   * @generated from field: string authority = 1;
   */
  authority = "";

  /**
   * @generated from field: cosmos.bank.v1beta1.Metadata metadata = 3;
   */
  metadata?: Metadata;

  constructor(data?: PartialMessage<MsgRegisterCoin>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "vsc.erc20.v1.MsgRegisterCoin";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "authority", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "metadata", kind: "message", T: Metadata },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgRegisterCoin {
    return new MsgRegisterCoin().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgRegisterCoin {
    return new MsgRegisterCoin().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgRegisterCoin {
    return new MsgRegisterCoin().fromJsonString(jsonString, options);
  }

  static equals(a: MsgRegisterCoin | PlainMessage<MsgRegisterCoin> | undefined, b: MsgRegisterCoin | PlainMessage<MsgRegisterCoin> | undefined): boolean {
    return proto3.util.equals(MsgRegisterCoin, a, b);
  }
}

/**
 * MsgRegisterCoinResponse returns the metadata of the registered coin.
 *
 * @generated from message vsc.erc20.v1.MsgRegisterCoinResponse
 */
export class MsgRegisterCoinResponse extends Message<MsgRegisterCoinResponse> {
  /**
   * @generated from field: vsc.erc20.v1.TokenPair pair = 1;
   */
  pair?: TokenPair;

  constructor(data?: PartialMessage<MsgRegisterCoinResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "vsc.erc20.v1.MsgRegisterCoinResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "pair", kind: "message", T: TokenPair },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgRegisterCoinResponse {
    return new MsgRegisterCoinResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgRegisterCoinResponse {
    return new MsgRegisterCoinResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgRegisterCoinResponse {
    return new MsgRegisterCoinResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgRegisterCoinResponse | PlainMessage<MsgRegisterCoinResponse> | undefined, b: MsgRegisterCoinResponse | PlainMessage<MsgRegisterCoinResponse> | undefined): boolean {
    return proto3.util.equals(MsgRegisterCoinResponse, a, b);
  }
}

/**
 * MsgUpdateParams is the Msg/UpdateParams request type for Erc20 parameters.
 *
 * @generated from message vsc.erc20.v1.MsgUpdateParams
 */
export class MsgUpdateParams extends Message<MsgUpdateParams> {
  /**
   * @generated from field: string authority = 1;
   */
  authority = "";

  /**
   * @generated from field: vsc.erc20.v1.Params params = 2;
   */
  params?: Params;

  constructor(data?: PartialMessage<MsgUpdateParams>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "vsc.erc20.v1.MsgUpdateParams";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "authority", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "params", kind: "message", T: Params },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateParams {
    return new MsgUpdateParams().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateParams {
    return new MsgUpdateParams().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateParams {
    return new MsgUpdateParams().fromJsonString(jsonString, options);
  }

  static equals(a: MsgUpdateParams | PlainMessage<MsgUpdateParams> | undefined, b: MsgUpdateParams | PlainMessage<MsgUpdateParams> | undefined): boolean {
    return proto3.util.equals(MsgUpdateParams, a, b);
  }
}

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 *
 * @generated from message vsc.erc20.v1.MsgUpdateParamsResponse
 */
export class MsgUpdateParamsResponse extends Message<MsgUpdateParamsResponse> {
  constructor(data?: PartialMessage<MsgUpdateParamsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "vsc.erc20.v1.MsgUpdateParamsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateParamsResponse {
    return new MsgUpdateParamsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateParamsResponse {
    return new MsgUpdateParamsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateParamsResponse {
    return new MsgUpdateParamsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgUpdateParamsResponse | PlainMessage<MsgUpdateParamsResponse> | undefined, b: MsgUpdateParamsResponse | PlainMessage<MsgUpdateParamsResponse> | undefined): boolean {
    return proto3.util.equals(MsgUpdateParamsResponse, a, b);
  }
}

/**
 * @generated from message vsc.erc20.v1.MsgMintCoins
 */
export class MsgMintCoins extends Message<MsgMintCoins> {
  /**
   * @generated from field: string authority = 1;
   */
  authority = "";

  /**
   * @generated from field: string recipient = 2;
   */
  recipient = "";

  /**
   * @generated from field: cosmos.base.v1beta1.Coin coin = 3;
   */
  coin?: Coin;

  constructor(data?: PartialMessage<MsgMintCoins>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "vsc.erc20.v1.MsgMintCoins";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "authority", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "recipient", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "coin", kind: "message", T: Coin },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgMintCoins {
    return new MsgMintCoins().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgMintCoins {
    return new MsgMintCoins().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgMintCoins {
    return new MsgMintCoins().fromJsonString(jsonString, options);
  }

  static equals(a: MsgMintCoins | PlainMessage<MsgMintCoins> | undefined, b: MsgMintCoins | PlainMessage<MsgMintCoins> | undefined): boolean {
    return proto3.util.equals(MsgMintCoins, a, b);
  }
}

/**
 * @generated from message vsc.erc20.v1.MsgMintCoinsResponse
 */
export class MsgMintCoinsResponse extends Message<MsgMintCoinsResponse> {
  constructor(data?: PartialMessage<MsgMintCoinsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "vsc.erc20.v1.MsgMintCoinsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgMintCoinsResponse {
    return new MsgMintCoinsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgMintCoinsResponse {
    return new MsgMintCoinsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgMintCoinsResponse {
    return new MsgMintCoinsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgMintCoinsResponse | PlainMessage<MsgMintCoinsResponse> | undefined, b: MsgMintCoinsResponse | PlainMessage<MsgMintCoinsResponse> | undefined): boolean {
    return proto3.util.equals(MsgMintCoinsResponse, a, b);
  }
}

/**
 * @generated from message vsc.erc20.v1.MsgBurnCoins
 */
export class MsgBurnCoins extends Message<MsgBurnCoins> {
  /**
   * @generated from field: string authority = 1;
   */
  authority = "";

  /**
   * @generated from field: string from = 2;
   */
  from = "";

  /**
   * @generated from field: cosmos.base.v1beta1.Coin coin = 3;
   */
  coin?: Coin;

  constructor(data?: PartialMessage<MsgBurnCoins>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "vsc.erc20.v1.MsgBurnCoins";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "authority", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "from", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "coin", kind: "message", T: Coin },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgBurnCoins {
    return new MsgBurnCoins().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgBurnCoins {
    return new MsgBurnCoins().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgBurnCoins {
    return new MsgBurnCoins().fromJsonString(jsonString, options);
  }

  static equals(a: MsgBurnCoins | PlainMessage<MsgBurnCoins> | undefined, b: MsgBurnCoins | PlainMessage<MsgBurnCoins> | undefined): boolean {
    return proto3.util.equals(MsgBurnCoins, a, b);
  }
}

/**
 * @generated from message vsc.erc20.v1.MsgBurnCoinsResponse
 */
export class MsgBurnCoinsResponse extends Message<MsgBurnCoinsResponse> {
  constructor(data?: PartialMessage<MsgBurnCoinsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "vsc.erc20.v1.MsgBurnCoinsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgBurnCoinsResponse {
    return new MsgBurnCoinsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgBurnCoinsResponse {
    return new MsgBurnCoinsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgBurnCoinsResponse {
    return new MsgBurnCoinsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgBurnCoinsResponse | PlainMessage<MsgBurnCoinsResponse> | undefined, b: MsgBurnCoinsResponse | PlainMessage<MsgBurnCoinsResponse> | undefined): boolean {
    return proto3.util.equals(MsgBurnCoinsResponse, a, b);
  }
}

