// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file terra/tax/v1beta1/query.proto (package terra.tax.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryBurnTaxRateRequest, QueryBurnTaxRateResponse, QueryParamsRequest, QueryParamsResponse } from "./query_pb.js";

const TYPE_NAME = "terra.tax.v1beta1.Query";

/**
 * @generated from rpc terra.tax.v1beta1.Query.Params
 */
export const QueryParamsService = {
  typeName: TYPE_NAME,
  method: "Params",
  Request: QueryParamsRequest,
  Response: QueryParamsResponse,
} as const;

/**
 * @generated from rpc terra.tax.v1beta1.Query.BurnTaxRate
 */
export const QueryBurnTaxRateService = {
  typeName: TYPE_NAME,
  method: "BurnTaxRate",
  Request: QueryBurnTaxRateRequest,
  Response: QueryBurnTaxRateResponse,
} as const;

