// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file terra/tax/v1beta1/tx.proto (package terra.tax.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgUpdateParams, MsgUpdateParamsResponse } from "./tx_pb.js";

const TYPE_NAME = "terra.tax.v1beta1.Msg";

/**
 * @generated from rpc terra.tax.v1beta1.Msg.UpdateParams
 */
export const MsgUpdateParamsService = {
  typeName: TYPE_NAME,
  method: "UpdateParams",
  Request: MsgUpdateParams,
  Response: MsgUpdateParamsResponse,
} as const;

