// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file ibc/applications/gmp/v1/account.proto (package ibc.applications.gmp.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Any, Message, proto3 } from "@bufbuild/protobuf";

/**
 * AccountIdentifier is used to identify a ICS27 account.
 *
 * @generated from message ibc.applications.gmp.v1.AccountIdentifier
 */
export class AccountIdentifier extends Message<AccountIdentifier> {
  /**
   * The (local) client identifier
   *
   * @generated from field: string client_id = 1;
   */
  clientId = "";

  /**
   * The sender of the packet
   *
   * @generated from field: string sender = 2;
   */
  sender = "";

  /**
   * The salt of the packet
   *
   * @generated from field: bytes salt = 3;
   */
  salt = new Uint8Array(0);

  constructor(data?: PartialMessage<AccountIdentifier>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ibc.applications.gmp.v1.AccountIdentifier";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "client_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "sender", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "salt", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AccountIdentifier {
    return new AccountIdentifier().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AccountIdentifier {
    return new AccountIdentifier().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AccountIdentifier {
    return new AccountIdentifier().fromJsonString(jsonString, options);
  }

  static equals(a: AccountIdentifier | PlainMessage<AccountIdentifier> | undefined, b: AccountIdentifier | PlainMessage<AccountIdentifier> | undefined): boolean {
    return proto3.util.equals(AccountIdentifier, a, b);
  }
}

/**
 * An ICS27Account is defined as a BaseAccount & the account identifier
 *
 * @generated from message ibc.applications.gmp.v1.ICS27Account
 */
export class ICS27Account extends Message<ICS27Account> {
  /**
   * @generated from field: string address = 1;
   */
  address = "";

  /**
   * @generated from field: ibc.applications.gmp.v1.AccountIdentifier account_id = 2;
   */
  accountId?: AccountIdentifier;

  constructor(data?: PartialMessage<ICS27Account>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ibc.applications.gmp.v1.ICS27Account";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "account_id", kind: "message", T: AccountIdentifier },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ICS27Account {
    return new ICS27Account().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ICS27Account {
    return new ICS27Account().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ICS27Account {
    return new ICS27Account().fromJsonString(jsonString, options);
  }

  static equals(a: ICS27Account | PlainMessage<ICS27Account> | undefined, b: ICS27Account | PlainMessage<ICS27Account> | undefined): boolean {
    return proto3.util.equals(ICS27Account, a, b);
  }
}

/**
 * CosmosTx contains a list of sdk.Msg's. It should be used when sending transactions to an SDK host chain.
 *
 * @generated from message ibc.applications.gmp.v1.CosmosTx
 */
export class CosmosTx extends Message<CosmosTx> {
  /**
   * @generated from field: repeated google.protobuf.Any messages = 1;
   */
  messages: Any[] = [];

  constructor(data?: PartialMessage<CosmosTx>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ibc.applications.gmp.v1.CosmosTx";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "messages", kind: "message", T: Any, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CosmosTx {
    return new CosmosTx().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CosmosTx {
    return new CosmosTx().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CosmosTx {
    return new CosmosTx().fromJsonString(jsonString, options);
  }

  static equals(a: CosmosTx | PlainMessage<CosmosTx> | undefined, b: CosmosTx | PlainMessage<CosmosTx> | undefined): boolean {
    return proto3.util.equals(CosmosTx, a, b);
  }
}

