// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file ibc/applications/gmp/v1/query.proto (package ibc.applications.gmp.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { AccountIdentifier } from "cosmes/protobufs/sdk53/ibc/applications/gmp/v1/account_pb.js";

/**
 * QueryAccountAddressRequest is the request type for the Query/AccountAddress RPC method.
 *
 * @generated from message ibc.applications.gmp.v1.QueryAccountAddressRequest
 */
export class QueryAccountAddressRequest extends Message<QueryAccountAddressRequest> {
  /**
   * The (local) client identifier
   *
   * @generated from field: string client_id = 1;
   */
  clientId = "";

  /**
   * The sender of the packet
   *
   * @generated from field: string sender = 2;
   */
  sender = "";

  /**
   * The salt of the packet (in hex format)
   *
   * @generated from field: string salt = 3;
   */
  salt = "";

  constructor(data?: PartialMessage<QueryAccountAddressRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ibc.applications.gmp.v1.QueryAccountAddressRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "client_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "sender", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "salt", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryAccountAddressRequest {
    return new QueryAccountAddressRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryAccountAddressRequest {
    return new QueryAccountAddressRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryAccountAddressRequest {
    return new QueryAccountAddressRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryAccountAddressRequest | PlainMessage<QueryAccountAddressRequest> | undefined, b: QueryAccountAddressRequest | PlainMessage<QueryAccountAddressRequest> | undefined): boolean {
    return proto3.util.equals(QueryAccountAddressRequest, a, b);
  }
}

/**
 * QueryAccountAddressResponse is the response type for the Query/AccountAddress RPC method.
 *
 * @generated from message ibc.applications.gmp.v1.QueryAccountAddressResponse
 */
export class QueryAccountAddressResponse extends Message<QueryAccountAddressResponse> {
  /**
   * The interchain account address
   *
   * @generated from field: string account_address = 1;
   */
  accountAddress = "";

  constructor(data?: PartialMessage<QueryAccountAddressResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ibc.applications.gmp.v1.QueryAccountAddressResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "account_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryAccountAddressResponse {
    return new QueryAccountAddressResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryAccountAddressResponse {
    return new QueryAccountAddressResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryAccountAddressResponse {
    return new QueryAccountAddressResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryAccountAddressResponse | PlainMessage<QueryAccountAddressResponse> | undefined, b: QueryAccountAddressResponse | PlainMessage<QueryAccountAddressResponse> | undefined): boolean {
    return proto3.util.equals(QueryAccountAddressResponse, a, b);
  }
}

/**
 * QueryAccountIdentifierRequest is the request type for querying the account identifier by account address.
 *
 * @generated from message ibc.applications.gmp.v1.QueryAccountIdentifierRequest
 */
export class QueryAccountIdentifierRequest extends Message<QueryAccountIdentifierRequest> {
  /**
   * @generated from field: string account_address = 1;
   */
  accountAddress = "";

  constructor(data?: PartialMessage<QueryAccountIdentifierRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ibc.applications.gmp.v1.QueryAccountIdentifierRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "account_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryAccountIdentifierRequest {
    return new QueryAccountIdentifierRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryAccountIdentifierRequest {
    return new QueryAccountIdentifierRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryAccountIdentifierRequest {
    return new QueryAccountIdentifierRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryAccountIdentifierRequest | PlainMessage<QueryAccountIdentifierRequest> | undefined, b: QueryAccountIdentifierRequest | PlainMessage<QueryAccountIdentifierRequest> | undefined): boolean {
    return proto3.util.equals(QueryAccountIdentifierRequest, a, b);
  }
}

/**
 * QueryAccountIdentifierResponse is the response type for querying the account identifier by account address.
 *
 * @generated from message ibc.applications.gmp.v1.QueryAccountIdentifierResponse
 */
export class QueryAccountIdentifierResponse extends Message<QueryAccountIdentifierResponse> {
  /**
   * @generated from field: ibc.applications.gmp.v1.AccountIdentifier account_id = 1;
   */
  accountId?: AccountIdentifier;

  constructor(data?: PartialMessage<QueryAccountIdentifierResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ibc.applications.gmp.v1.QueryAccountIdentifierResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "account_id", kind: "message", T: AccountIdentifier },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryAccountIdentifierResponse {
    return new QueryAccountIdentifierResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryAccountIdentifierResponse {
    return new QueryAccountIdentifierResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryAccountIdentifierResponse {
    return new QueryAccountIdentifierResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryAccountIdentifierResponse | PlainMessage<QueryAccountIdentifierResponse> | undefined, b: QueryAccountIdentifierResponse | PlainMessage<QueryAccountIdentifierResponse> | undefined): boolean {
    return proto3.util.equals(QueryAccountIdentifierResponse, a, b);
  }
}

