// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file ibc/applications/gmp/v1/tx.proto (package ibc.applications.gmp.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * MsgSendCall defines a msg to send a call to a contract/receiver on a ICS27-2 enabled chain.
 *
 * @generated from message ibc.applications.gmp.v1.MsgSendCall
 */
export class MsgSendCall extends Message<MsgSendCall> {
  /**
   * the client by which the packet will be sent
   *
   * @generated from field: string source_client = 1;
   */
  sourceClient = "";

  /**
   * the sender address
   *
   * @generated from field: string sender = 2;
   */
  sender = "";

  /**
   * the recipient address on the destination chain
   *
   * @generated from field: string receiver = 3;
   */
  receiver = "";

  /**
   * The salt used to generate the caller account address
   *
   * @generated from field: bytes salt = 4;
   */
  salt = new Uint8Array(0);

  /**
   * The payload of the call
   *
   * @generated from field: bytes payload = 5;
   */
  payload = new Uint8Array(0);

  /**
   * Timeout timestamp in absolute nanoseconds since unix epoch.
   *
   * @generated from field: uint64 timeout_timestamp = 6;
   */
  timeoutTimestamp = protoInt64.zero;

  /**
   * optional memo
   *
   * @generated from field: string memo = 7;
   */
  memo = "";

  /**
   * optional encoding
   *
   * @generated from field: string encoding = 8;
   */
  encoding = "";

  constructor(data?: PartialMessage<MsgSendCall>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ibc.applications.gmp.v1.MsgSendCall";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "source_client", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "sender", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "receiver", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "salt", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 5, name: "payload", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 6, name: "timeout_timestamp", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 7, name: "memo", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "encoding", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgSendCall {
    return new MsgSendCall().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgSendCall {
    return new MsgSendCall().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgSendCall {
    return new MsgSendCall().fromJsonString(jsonString, options);
  }

  static equals(a: MsgSendCall | PlainMessage<MsgSendCall> | undefined, b: MsgSendCall | PlainMessage<MsgSendCall> | undefined): boolean {
    return proto3.util.equals(MsgSendCall, a, b);
  }
}

/**
 * MsgSendCallResponse defines the Msg/SendCall response type.
 *
 * @generated from message ibc.applications.gmp.v1.MsgSendCallResponse
 */
export class MsgSendCallResponse extends Message<MsgSendCallResponse> {
  /**
   * sequence number of the GMP packet sent
   *
   * @generated from field: uint64 sequence = 1;
   */
  sequence = protoInt64.zero;

  constructor(data?: PartialMessage<MsgSendCallResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ibc.applications.gmp.v1.MsgSendCallResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "sequence", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgSendCallResponse {
    return new MsgSendCallResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgSendCallResponse {
    return new MsgSendCallResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgSendCallResponse {
    return new MsgSendCallResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgSendCallResponse | PlainMessage<MsgSendCallResponse> | undefined, b: MsgSendCallResponse | PlainMessage<MsgSendCallResponse> | undefined): boolean {
    return proto3.util.equals(MsgSendCallResponse, a, b);
  }
}

