// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file vsc/oracle/v1/tx.proto (package vsc.oracle.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgAggregateExchangeRatePrevote, MsgAggregateExchangeRatePrevoteResponse, MsgAggregateExchangeRateVote, MsgAggregateExchangeRateVoteResponse, MsgDelegateFeedConsent, MsgDelegateFeedConsentResponse, MsgEditOracleParams, MsgEditOracleParamsResponse } from "./tx_pb.js";

const TYPE_NAME = "vsc.oracle.v1.Msg";

/**
 * AggregateExchangeRatePrevote defines a method for submitting
 * aggregate exchange rate prevote
 *
 * @generated from rpc vsc.oracle.v1.Msg.AggregateExchangeRatePrevote
 */
export const MsgAggregateExchangeRatePrevoteService = {
  typeName: TYPE_NAME,
  method: "AggregateExchangeRatePrevote",
  Request: MsgAggregateExchangeRatePrevote,
  Response: MsgAggregateExchangeRatePrevoteResponse,
} as const;

/**
 * AggregateExchangeRateVote defines a method for submitting
 * aggregate exchange rate vote
 *
 * @generated from rpc vsc.oracle.v1.Msg.AggregateExchangeRateVote
 */
export const MsgAggregateExchangeRateVoteService = {
  typeName: TYPE_NAME,
  method: "AggregateExchangeRateVote",
  Request: MsgAggregateExchangeRateVote,
  Response: MsgAggregateExchangeRateVoteResponse,
} as const;

/**
 * DelegateFeedConsent defines a method for delegating oracle voting rights
 * to another address known as a price feeder.
 * See https://github.com/vsc-blockchain/pricefeeder.
 *
 * @generated from rpc vsc.oracle.v1.Msg.DelegateFeedConsent
 */
export const MsgDelegateFeedConsentService = {
  typeName: TYPE_NAME,
  method: "DelegateFeedConsent",
  Request: MsgDelegateFeedConsent,
  Response: MsgDelegateFeedConsentResponse,
} as const;

/**
 * Dummy comment to avoid reformatting
 *
 * @generated from rpc vsc.oracle.v1.Msg.EditOracleParams
 */
export const MsgEditOracleParamsService = {
  typeName: TYPE_NAME,
  method: "EditOracleParams",
  Request: MsgEditOracleParams,
  Response: MsgEditOracleParamsResponse,
} as const;

