// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file terra/wasm/v1beta1/genesis.proto (package terra.wasm.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { LegacyCodeInfo, LegacyContractInfo } from "cosmes/protobufs/sdk53/terra/wasm/v1beta1/wasm_pb.js";

/**
 * Model is a struct that holds a KV pair
 *
 * @generated from message terra.wasm.v1beta1.Model
 */
export class Model extends Message<Model> {
  /**
   * @generated from field: bytes key = 1;
   */
  key = new Uint8Array(0);

  /**
   * @generated from field: bytes value = 2;
   */
  value = new Uint8Array(0);

  constructor(data?: PartialMessage<Model>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.wasm.v1beta1.Model";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "key", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 2, name: "value", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Model {
    return new Model().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Model {
    return new Model().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Model {
    return new Model().fromJsonString(jsonString, options);
  }

  static equals(a: Model | PlainMessage<Model> | undefined, b: Model | PlainMessage<Model> | undefined): boolean {
    return proto3.util.equals(Model, a, b);
  }
}

/**
 * Code struct encompasses CodeInfo and CodeBytes
 *
 * @generated from message terra.wasm.v1beta1.Code
 */
export class Code extends Message<Code> {
  /**
   * @generated from field: terra.wasm.v1beta1.LegacyCodeInfo code_info = 1;
   */
  codeInfo?: LegacyCodeInfo;

  /**
   * @generated from field: bytes code_bytes = 2;
   */
  codeBytes = new Uint8Array(0);

  constructor(data?: PartialMessage<Code>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.wasm.v1beta1.Code";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "code_info", kind: "message", T: LegacyCodeInfo },
    { no: 2, name: "code_bytes", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Code {
    return new Code().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Code {
    return new Code().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Code {
    return new Code().fromJsonString(jsonString, options);
  }

  static equals(a: Code | PlainMessage<Code> | undefined, b: Code | PlainMessage<Code> | undefined): boolean {
    return proto3.util.equals(Code, a, b);
  }
}

/**
 * Contract struct encompasses ContractAddress, ContractInfo, and ContractState
 *
 * @generated from message terra.wasm.v1beta1.Contract
 */
export class Contract extends Message<Contract> {
  /**
   * @generated from field: terra.wasm.v1beta1.LegacyContractInfo contract_info = 1;
   */
  contractInfo?: LegacyContractInfo;

  /**
   * @generated from field: repeated terra.wasm.v1beta1.Model contract_store = 2;
   */
  contractStore: Model[] = [];

  constructor(data?: PartialMessage<Contract>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.wasm.v1beta1.Contract";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "contract_info", kind: "message", T: LegacyContractInfo },
    { no: 2, name: "contract_store", kind: "message", T: Model, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Contract {
    return new Contract().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Contract {
    return new Contract().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Contract {
    return new Contract().fromJsonString(jsonString, options);
  }

  static equals(a: Contract | PlainMessage<Contract> | undefined, b: Contract | PlainMessage<Contract> | undefined): boolean {
    return proto3.util.equals(Contract, a, b);
  }
}

