// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file terra/wasm/v1beta1/tx.proto (package terra.wasm.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgClearContractAdmin, MsgClearContractAdminResponse, MsgExecuteContract, MsgExecuteContractResponse, MsgInstantiateContract, MsgInstantiateContractResponse, MsgMigrateCode, MsgMigrateCodeResponse, MsgMigrateContract, MsgMigrateContractResponse, MsgStoreCode, MsgStoreCodeResponse, MsgUpdateContractAdmin, MsgUpdateContractAdminResponse } from "./tx_pb.js";

const TYPE_NAME = "terra.wasm.v1beta1.Msg";

/**
 * StoreCode to submit Wasm code to the system
 *
 * @generated from rpc terra.wasm.v1beta1.Msg.StoreCode
 */
export const MsgStoreCodeService = {
  typeName: TYPE_NAME,
  method: "StoreCode",
  Request: MsgStoreCode,
  Response: MsgStoreCodeResponse,
} as const;

/**
 * MigrateCode to submit new version Wasm code to the system
 *
 * @generated from rpc terra.wasm.v1beta1.Msg.MigrateCode
 */
export const MsgMigrateCodeService = {
  typeName: TYPE_NAME,
  method: "MigrateCode",
  Request: MsgMigrateCode,
  Response: MsgMigrateCodeResponse,
} as const;

/**
 *  Instantiate creates a new smart contract instance for the given code id.
 *
 * @generated from rpc terra.wasm.v1beta1.Msg.InstantiateContract
 */
export const MsgInstantiateContractService = {
  typeName: TYPE_NAME,
  method: "InstantiateContract",
  Request: MsgInstantiateContract,
  Response: MsgInstantiateContractResponse,
} as const;

/**
 * Execute submits the given message data to a smart contract
 *
 * @generated from rpc terra.wasm.v1beta1.Msg.ExecuteContract
 */
export const MsgExecuteContractService = {
  typeName: TYPE_NAME,
  method: "ExecuteContract",
  Request: MsgExecuteContract,
  Response: MsgExecuteContractResponse,
} as const;

/**
 * Migrate runs a code upgrade/ downgrade for a smart contract
 *
 * @generated from rpc terra.wasm.v1beta1.Msg.MigrateContract
 */
export const MsgMigrateContractService = {
  typeName: TYPE_NAME,
  method: "MigrateContract",
  Request: MsgMigrateContract,
  Response: MsgMigrateContractResponse,
} as const;

/**
 * UpdateContractAdmin sets a new admin for a smart contract
 *
 * @generated from rpc terra.wasm.v1beta1.Msg.UpdateContractAdmin
 */
export const MsgUpdateContractAdminService = {
  typeName: TYPE_NAME,
  method: "UpdateContractAdmin",
  Request: MsgUpdateContractAdmin,
  Response: MsgUpdateContractAdminResponse,
} as const;

/**
 * ClearContractAdmin remove admin flag from a smart contract
 *
 * @generated from rpc terra.wasm.v1beta1.Msg.ClearContractAdmin
 */
export const MsgClearContractAdminService = {
  typeName: TYPE_NAME,
  method: "ClearContractAdmin",
  Request: MsgClearContractAdmin,
  Response: MsgClearContractAdminResponse,
} as const;

