// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file terra/wasm/v1beta1/tx.proto (package terra.wasm.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { Coin } from "cosmes/protobufs/sdk53/cosmos/base/v1beta1/coin_pb.js";

/**
 * MsgStoreCode represents a message to submit
 * Wasm code to the system
 *
 * @generated from message terra.wasm.v1beta1.MsgStoreCode
 */
export class MsgStoreCode extends Message<MsgStoreCode> {
  /**
   * Sender is the that actor that signed the messages
   *
   * @generated from field: string sender = 1;
   */
  sender = "";

  /**
   * WASMByteCode can be raw or gzip compressed
   *
   * @generated from field: bytes wasm_byte_code = 2;
   */
  wasmByteCode = new Uint8Array(0);

  constructor(data?: PartialMessage<MsgStoreCode>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.wasm.v1beta1.MsgStoreCode";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "sender", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "wasm_byte_code", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgStoreCode {
    return new MsgStoreCode().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgStoreCode {
    return new MsgStoreCode().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgStoreCode {
    return new MsgStoreCode().fromJsonString(jsonString, options);
  }

  static equals(a: MsgStoreCode | PlainMessage<MsgStoreCode> | undefined, b: MsgStoreCode | PlainMessage<MsgStoreCode> | undefined): boolean {
    return proto3.util.equals(MsgStoreCode, a, b);
  }
}

/**
 * MsgStoreCodeResponse defines the Msg/StoreCode response type.
 *
 * @generated from message terra.wasm.v1beta1.MsgStoreCodeResponse
 */
export class MsgStoreCodeResponse extends Message<MsgStoreCodeResponse> {
  /**
   * CodeID is the reference to the stored WASM code
   *
   * @generated from field: uint64 code_id = 1;
   */
  codeId = protoInt64.zero;

  constructor(data?: PartialMessage<MsgStoreCodeResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.wasm.v1beta1.MsgStoreCodeResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "code_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgStoreCodeResponse {
    return new MsgStoreCodeResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgStoreCodeResponse {
    return new MsgStoreCodeResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgStoreCodeResponse {
    return new MsgStoreCodeResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgStoreCodeResponse | PlainMessage<MsgStoreCodeResponse> | undefined, b: MsgStoreCodeResponse | PlainMessage<MsgStoreCodeResponse> | undefined): boolean {
    return proto3.util.equals(MsgStoreCodeResponse, a, b);
  }
}

/**
 * MsgMigrateCode represents a message to submit
 * Wasm code to the system
 *
 * @generated from message terra.wasm.v1beta1.MsgMigrateCode
 */
export class MsgMigrateCode extends Message<MsgMigrateCode> {
  /**
   * CodeID is the migration target code id
   *
   * @generated from field: uint64 code_id = 1;
   */
  codeId = protoInt64.zero;

  /**
   * Sender is the that actor that signed the messages
   *
   * @generated from field: string sender = 2;
   */
  sender = "";

  /**
   * WASMByteCode can be raw or gzip compressed
   *
   * @generated from field: bytes wasm_byte_code = 3;
   */
  wasmByteCode = new Uint8Array(0);

  constructor(data?: PartialMessage<MsgMigrateCode>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.wasm.v1beta1.MsgMigrateCode";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "code_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "sender", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "wasm_byte_code", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgMigrateCode {
    return new MsgMigrateCode().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgMigrateCode {
    return new MsgMigrateCode().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgMigrateCode {
    return new MsgMigrateCode().fromJsonString(jsonString, options);
  }

  static equals(a: MsgMigrateCode | PlainMessage<MsgMigrateCode> | undefined, b: MsgMigrateCode | PlainMessage<MsgMigrateCode> | undefined): boolean {
    return proto3.util.equals(MsgMigrateCode, a, b);
  }
}

/**
 * MsgMigrateCodeResponse defines the Msg/MigrateCode response type.
 *
 * @generated from message terra.wasm.v1beta1.MsgMigrateCodeResponse
 */
export class MsgMigrateCodeResponse extends Message<MsgMigrateCodeResponse> {
  constructor(data?: PartialMessage<MsgMigrateCodeResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.wasm.v1beta1.MsgMigrateCodeResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgMigrateCodeResponse {
    return new MsgMigrateCodeResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgMigrateCodeResponse {
    return new MsgMigrateCodeResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgMigrateCodeResponse {
    return new MsgMigrateCodeResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgMigrateCodeResponse | PlainMessage<MsgMigrateCodeResponse> | undefined, b: MsgMigrateCodeResponse | PlainMessage<MsgMigrateCodeResponse> | undefined): boolean {
    return proto3.util.equals(MsgMigrateCodeResponse, a, b);
  }
}

/**
 * MsgInstantiateContract represents a message to create
 * a new smart contract instance for the given
 * code id.
 *
 * @generated from message terra.wasm.v1beta1.MsgInstantiateContract
 */
export class MsgInstantiateContract extends Message<MsgInstantiateContract> {
  /**
   * Sender is an sender address
   *
   * @generated from field: string sender = 1;
   */
  sender = "";

  /**
   * Admin is an optional admin address who can migrate the contract
   *
   * @generated from field: string admin = 2;
   */
  admin = "";

  /**
   * CodeID is the reference to the stored WASM code
   *
   * @generated from field: uint64 code_id = 3;
   */
  codeId = protoInt64.zero;

  /**
   * InitMsg json encoded message to be passed to the contract on instantiation
   *
   * @generated from field: bytes init_msg = 4;
   */
  initMsg = new Uint8Array(0);

  /**
   * InitCoins that are transferred to the contract on execution
   *
   * @generated from field: repeated cosmos.base.v1beta1.Coin init_coins = 5;
   */
  initCoins: Coin[] = [];

  constructor(data?: PartialMessage<MsgInstantiateContract>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.wasm.v1beta1.MsgInstantiateContract";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "sender", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "admin", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "code_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "init_msg", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 5, name: "init_coins", kind: "message", T: Coin, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgInstantiateContract {
    return new MsgInstantiateContract().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgInstantiateContract {
    return new MsgInstantiateContract().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgInstantiateContract {
    return new MsgInstantiateContract().fromJsonString(jsonString, options);
  }

  static equals(a: MsgInstantiateContract | PlainMessage<MsgInstantiateContract> | undefined, b: MsgInstantiateContract | PlainMessage<MsgInstantiateContract> | undefined): boolean {
    return proto3.util.equals(MsgInstantiateContract, a, b);
  }
}

/**
 * MsgInstantiateContractResponse defines the Msg/InstantiateContract response type.
 *
 * @generated from message terra.wasm.v1beta1.MsgInstantiateContractResponse
 */
export class MsgInstantiateContractResponse extends Message<MsgInstantiateContractResponse> {
  /**
   * ContractAddress is the bech32 address of the new contract instance.
   *
   * @generated from field: string contract_address = 1;
   */
  contractAddress = "";

  /**
   * Data contains base64-encoded bytes to returned from the contract
   *
   * @generated from field: bytes data = 2;
   */
  data = new Uint8Array(0);

  constructor(data?: PartialMessage<MsgInstantiateContractResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.wasm.v1beta1.MsgInstantiateContractResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "contract_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "data", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgInstantiateContractResponse {
    return new MsgInstantiateContractResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgInstantiateContractResponse {
    return new MsgInstantiateContractResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgInstantiateContractResponse {
    return new MsgInstantiateContractResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgInstantiateContractResponse | PlainMessage<MsgInstantiateContractResponse> | undefined, b: MsgInstantiateContractResponse | PlainMessage<MsgInstantiateContractResponse> | undefined): boolean {
    return proto3.util.equals(MsgInstantiateContractResponse, a, b);
  }
}

/**
 * MsgExecuteContract represents a message to
 * submits the given message data to a smart contract.
 *
 * @generated from message terra.wasm.v1beta1.MsgExecuteContract
 */
export class MsgExecuteContract extends Message<MsgExecuteContract> {
  /**
   * Sender is the that actor that signed the messages
   *
   * @generated from field: string sender = 1;
   */
  sender = "";

  /**
   * Contract is the address of the smart contract
   *
   * @generated from field: string contract = 2;
   */
  contract = "";

  /**
   * ExecuteMsg json encoded message to be passed to the contract
   *
   * @generated from field: bytes execute_msg = 3;
   */
  executeMsg = new Uint8Array(0);

  /**
   * Coins that are transferred to the contract on execution
   *
   * @generated from field: repeated cosmos.base.v1beta1.Coin coins = 5;
   */
  coins: Coin[] = [];

  constructor(data?: PartialMessage<MsgExecuteContract>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.wasm.v1beta1.MsgExecuteContract";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "sender", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "contract", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "execute_msg", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 5, name: "coins", kind: "message", T: Coin, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgExecuteContract {
    return new MsgExecuteContract().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgExecuteContract {
    return new MsgExecuteContract().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgExecuteContract {
    return new MsgExecuteContract().fromJsonString(jsonString, options);
  }

  static equals(a: MsgExecuteContract | PlainMessage<MsgExecuteContract> | undefined, b: MsgExecuteContract | PlainMessage<MsgExecuteContract> | undefined): boolean {
    return proto3.util.equals(MsgExecuteContract, a, b);
  }
}

/**
 * MsgExecuteContractResponse defines the Msg/ExecuteContract response type.
 *
 * @generated from message terra.wasm.v1beta1.MsgExecuteContractResponse
 */
export class MsgExecuteContractResponse extends Message<MsgExecuteContractResponse> {
  /**
   * Data contains base64-encoded bytes to returned from the contract
   *
   * @generated from field: bytes data = 1;
   */
  data = new Uint8Array(0);

  constructor(data?: PartialMessage<MsgExecuteContractResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.wasm.v1beta1.MsgExecuteContractResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "data", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgExecuteContractResponse {
    return new MsgExecuteContractResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgExecuteContractResponse {
    return new MsgExecuteContractResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgExecuteContractResponse {
    return new MsgExecuteContractResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgExecuteContractResponse | PlainMessage<MsgExecuteContractResponse> | undefined, b: MsgExecuteContractResponse | PlainMessage<MsgExecuteContractResponse> | undefined): boolean {
    return proto3.util.equals(MsgExecuteContractResponse, a, b);
  }
}

/**
 * MsgMigrateContract represents a message to
 * runs a code upgrade/ downgrade for a smart contract
 *
 * @generated from message terra.wasm.v1beta1.MsgMigrateContract
 */
export class MsgMigrateContract extends Message<MsgMigrateContract> {
  /**
   * Admin is the current contract admin
   *
   * @generated from field: string admin = 1;
   */
  admin = "";

  /**
   * Contract is the address of the smart contract
   *
   * @generated from field: string contract = 2;
   */
  contract = "";

  /**
   * NewCodeID references the new WASM code
   *
   * @generated from field: uint64 new_code_id = 3;
   */
  newCodeId = protoInt64.zero;

  /**
   * MigrateMsg is json encoded message to be passed to the contract on migration
   *
   * @generated from field: bytes migrate_msg = 4;
   */
  migrateMsg = new Uint8Array(0);

  constructor(data?: PartialMessage<MsgMigrateContract>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.wasm.v1beta1.MsgMigrateContract";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "admin", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "contract", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "new_code_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "migrate_msg", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgMigrateContract {
    return new MsgMigrateContract().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgMigrateContract {
    return new MsgMigrateContract().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgMigrateContract {
    return new MsgMigrateContract().fromJsonString(jsonString, options);
  }

  static equals(a: MsgMigrateContract | PlainMessage<MsgMigrateContract> | undefined, b: MsgMigrateContract | PlainMessage<MsgMigrateContract> | undefined): boolean {
    return proto3.util.equals(MsgMigrateContract, a, b);
  }
}

/**
 * MsgMigrateContractResponse defines the Msg/MigrateContract response type.
 *
 * @generated from message terra.wasm.v1beta1.MsgMigrateContractResponse
 */
export class MsgMigrateContractResponse extends Message<MsgMigrateContractResponse> {
  /**
   * Data contains base64-encoded bytes to returned from the contract
   *
   * @generated from field: bytes data = 1;
   */
  data = new Uint8Array(0);

  constructor(data?: PartialMessage<MsgMigrateContractResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.wasm.v1beta1.MsgMigrateContractResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "data", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgMigrateContractResponse {
    return new MsgMigrateContractResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgMigrateContractResponse {
    return new MsgMigrateContractResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgMigrateContractResponse {
    return new MsgMigrateContractResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgMigrateContractResponse | PlainMessage<MsgMigrateContractResponse> | undefined, b: MsgMigrateContractResponse | PlainMessage<MsgMigrateContractResponse> | undefined): boolean {
    return proto3.util.equals(MsgMigrateContractResponse, a, b);
  }
}

/**
 * MsgUpdateContractAdmin represents a message to
 * sets a new admin for a smart contract
 *
 * @generated from message terra.wasm.v1beta1.MsgUpdateContractAdmin
 */
export class MsgUpdateContractAdmin extends Message<MsgUpdateContractAdmin> {
  /**
   * Admin is the current contract admin
   *
   * @generated from field: string admin = 1;
   */
  admin = "";

  /**
   * NewAdmin is the new contract admin
   *
   * @generated from field: string new_admin = 2;
   */
  newAdmin = "";

  /**
   * Contract is the address of the smart contract
   *
   * @generated from field: string contract = 3;
   */
  contract = "";

  constructor(data?: PartialMessage<MsgUpdateContractAdmin>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.wasm.v1beta1.MsgUpdateContractAdmin";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "admin", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "new_admin", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "contract", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateContractAdmin {
    return new MsgUpdateContractAdmin().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateContractAdmin {
    return new MsgUpdateContractAdmin().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateContractAdmin {
    return new MsgUpdateContractAdmin().fromJsonString(jsonString, options);
  }

  static equals(a: MsgUpdateContractAdmin | PlainMessage<MsgUpdateContractAdmin> | undefined, b: MsgUpdateContractAdmin | PlainMessage<MsgUpdateContractAdmin> | undefined): boolean {
    return proto3.util.equals(MsgUpdateContractAdmin, a, b);
  }
}

/**
 * MsgUpdateContractAdminResponse defines the Msg/UpdateContractAdmin response type.
 *
 * @generated from message terra.wasm.v1beta1.MsgUpdateContractAdminResponse
 */
export class MsgUpdateContractAdminResponse extends Message<MsgUpdateContractAdminResponse> {
  constructor(data?: PartialMessage<MsgUpdateContractAdminResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.wasm.v1beta1.MsgUpdateContractAdminResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateContractAdminResponse {
    return new MsgUpdateContractAdminResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateContractAdminResponse {
    return new MsgUpdateContractAdminResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateContractAdminResponse {
    return new MsgUpdateContractAdminResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgUpdateContractAdminResponse | PlainMessage<MsgUpdateContractAdminResponse> | undefined, b: MsgUpdateContractAdminResponse | PlainMessage<MsgUpdateContractAdminResponse> | undefined): boolean {
    return proto3.util.equals(MsgUpdateContractAdminResponse, a, b);
  }
}

/**
 * MsgClearContractAdmin represents a message to
 * clear admin address from a smart contract
 *
 * @generated from message terra.wasm.v1beta1.MsgClearContractAdmin
 */
export class MsgClearContractAdmin extends Message<MsgClearContractAdmin> {
  /**
   * Admin is the current contract admin
   *
   * @generated from field: string admin = 1;
   */
  admin = "";

  /**
   * Contract is the address of the smart contract
   *
   * @generated from field: string contract = 2;
   */
  contract = "";

  constructor(data?: PartialMessage<MsgClearContractAdmin>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.wasm.v1beta1.MsgClearContractAdmin";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "admin", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "contract", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgClearContractAdmin {
    return new MsgClearContractAdmin().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgClearContractAdmin {
    return new MsgClearContractAdmin().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgClearContractAdmin {
    return new MsgClearContractAdmin().fromJsonString(jsonString, options);
  }

  static equals(a: MsgClearContractAdmin | PlainMessage<MsgClearContractAdmin> | undefined, b: MsgClearContractAdmin | PlainMessage<MsgClearContractAdmin> | undefined): boolean {
    return proto3.util.equals(MsgClearContractAdmin, a, b);
  }
}

/**
 * MsgClearContractAdminResponse defines the Msg/ClearContractAdmin response type.
 *
 * @generated from message terra.wasm.v1beta1.MsgClearContractAdminResponse
 */
export class MsgClearContractAdminResponse extends Message<MsgClearContractAdminResponse> {
  constructor(data?: PartialMessage<MsgClearContractAdminResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.wasm.v1beta1.MsgClearContractAdminResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgClearContractAdminResponse {
    return new MsgClearContractAdminResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgClearContractAdminResponse {
    return new MsgClearContractAdminResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgClearContractAdminResponse {
    return new MsgClearContractAdminResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgClearContractAdminResponse | PlainMessage<MsgClearContractAdminResponse> | undefined, b: MsgClearContractAdminResponse | PlainMessage<MsgClearContractAdminResponse> | undefined): boolean {
    return proto3.util.equals(MsgClearContractAdminResponse, a, b);
  }
}

