// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file cosmos/protocolpool/v1/query.proto (package cosmos.protocolpool.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryCommunityPoolRequest, QueryCommunityPoolResponse, QueryContinuousFundRequest, QueryContinuousFundResponse, QueryContinuousFundsRequest, QueryContinuousFundsResponse, QueryParamsRequest, QueryParamsResponse } from "./query_pb.js";

const TYPE_NAME = "cosmos.protocolpool.v1.Query";

/**
 * CommunityPool queries the community pool coins.
 *
 * @generated from rpc cosmos.protocolpool.v1.Query.CommunityPool
 */
export const QueryCommunityPoolService = {
  typeName: TYPE_NAME,
  method: "CommunityPool",
  Request: QueryCommunityPoolRequest,
  Response: QueryCommunityPoolResponse,
} as const;

/**
 * ContinuousFund queries a continuous fund by the recipient is is associated with.
 *
 * @generated from rpc cosmos.protocolpool.v1.Query.ContinuousFund
 */
export const QueryContinuousFundService = {
  typeName: TYPE_NAME,
  method: "ContinuousFund",
  Request: QueryContinuousFundRequest,
  Response: QueryContinuousFundResponse,
} as const;

/**
 * ContinuousFunds queries all continuous funds in the store.
 *
 * @generated from rpc cosmos.protocolpool.v1.Query.ContinuousFunds
 */
export const QueryContinuousFundsService = {
  typeName: TYPE_NAME,
  method: "ContinuousFunds",
  Request: QueryContinuousFundsRequest,
  Response: QueryContinuousFundsResponse,
} as const;

/**
 * Params returns the total set of x/protocolpool parameters.
 *
 * @generated from rpc cosmos.protocolpool.v1.Query.Params
 */
export const QueryParamsService = {
  typeName: TYPE_NAME,
  method: "Params",
  Request: QueryParamsRequest,
  Response: QueryParamsResponse,
} as const;

