// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file cosmos/protocolpool/v1/tx.proto (package cosmos.protocolpool.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgCancelContinuousFund, MsgCancelContinuousFundResponse, MsgCommunityPoolSpend, MsgCommunityPoolSpendResponse, MsgCreateContinuousFund, MsgCreateContinuousFundResponse, MsgFundCommunityPool, MsgFundCommunityPoolResponse, MsgUpdateParams, MsgUpdateParamsResponse } from "./tx_pb.js";

const TYPE_NAME = "cosmos.protocolpool.v1.Msg";

/**
 * FundCommunityPool defines a method to allow an account to directly
 * fund the community pool.
 *
 * @generated from rpc cosmos.protocolpool.v1.Msg.FundCommunityPool
 */
export const MsgFundCommunityPoolService = {
  typeName: TYPE_NAME,
  method: "FundCommunityPool",
  Request: MsgFundCommunityPool,
  Response: MsgFundCommunityPoolResponse,
} as const;

/**
 * CommunityPoolSpend defines a governance operation for sending tokens from
 * the community pool in the x/protocolpool module to another account, which
 * could be the governance module itself. The authority is defined in the
 * keeper.
 *
 * @generated from rpc cosmos.protocolpool.v1.Msg.CommunityPoolSpend
 */
export const MsgCommunityPoolSpendService = {
  typeName: TYPE_NAME,
  method: "CommunityPoolSpend",
  Request: MsgCommunityPoolSpend,
  Response: MsgCommunityPoolSpendResponse,
} as const;

/**
 * CreateContinuousFund defines a method to distribute a percentage of funds to an address continuously.
 * This ContinuousFund can be indefinite or run until a given expiry time.
 * Funds come from validator block rewards from x/distribution, but may also come from
 * any user who funds the ProtocolPoolEscrow module account directly through x/bank.
 *
 * @generated from rpc cosmos.protocolpool.v1.Msg.CreateContinuousFund
 */
export const MsgCreateContinuousFundService = {
  typeName: TYPE_NAME,
  method: "CreateContinuousFund",
  Request: MsgCreateContinuousFund,
  Response: MsgCreateContinuousFundResponse,
} as const;

/**
 * CancelContinuousFund defines a method for cancelling continuous fund.
 *
 * @generated from rpc cosmos.protocolpool.v1.Msg.CancelContinuousFund
 */
export const MsgCancelContinuousFundService = {
  typeName: TYPE_NAME,
  method: "CancelContinuousFund",
  Request: MsgCancelContinuousFund,
  Response: MsgCancelContinuousFundResponse,
} as const;

/**
 * UpdateParams defines a governance operation for updating the x/protocolpool module parameters.
 * The authority is defined in the keeper.
 *
 * @generated from rpc cosmos.protocolpool.v1.Msg.UpdateParams
 */
export const MsgUpdateParamsService = {
  typeName: TYPE_NAME,
  method: "UpdateParams",
  Request: MsgUpdateParams,
  Response: MsgUpdateParamsResponse,
} as const;

