// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file terra/market/v1beta1/market.proto (package terra.market.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * Params defines the parameters for the market module.
 *
 * @generated from message terra.market.v1beta1.Params
 */
export class Params extends Message<Params> {
  /**
   * @generated from field: bytes base_pool = 1;
   */
  basePool = new Uint8Array(0);

  /**
   * @generated from field: uint64 pool_recovery_period = 2;
   */
  poolRecoveryPeriod = protoInt64.zero;

  /**
   * @generated from field: bytes min_stability_spread = 3;
   */
  minStabilitySpread = new Uint8Array(0);

  constructor(data?: PartialMessage<Params>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.market.v1beta1.Params";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "base_pool", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 2, name: "pool_recovery_period", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "min_stability_spread", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Params {
    return new Params().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Params {
    return new Params().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Params {
    return new Params().fromJsonString(jsonString, options);
  }

  static equals(a: Params | PlainMessage<Params> | undefined, b: Params | PlainMessage<Params> | undefined): boolean {
    return proto3.util.equals(Params, a, b);
  }
}

