// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file terra/market/v1beta1/query.proto (package terra.market.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryParamsRequest, QueryParamsResponse, QuerySwapRequest, QuerySwapResponse, QueryTerraPoolDeltaRequest, QueryTerraPoolDeltaResponse } from "./query_pb.js";

const TYPE_NAME = "terra.market.v1beta1.Query";

/**
 * Swap returns simulated swap amount.
 *
 * @generated from rpc terra.market.v1beta1.Query.Swap
 */
export const QuerySwapService = {
  typeName: TYPE_NAME,
  method: "Swap",
  Request: QuerySwapRequest,
  Response: QuerySwapResponse,
} as const;

/**
 * TerraPoolDelta returns terra_pool_delta amount.
 *
 * @generated from rpc terra.market.v1beta1.Query.TerraPoolDelta
 */
export const QueryTerraPoolDeltaService = {
  typeName: TYPE_NAME,
  method: "TerraPoolDelta",
  Request: QueryTerraPoolDeltaRequest,
  Response: QueryTerraPoolDeltaResponse,
} as const;

/**
 * Params queries all parameters.
 *
 * @generated from rpc terra.market.v1beta1.Query.Params
 */
export const QueryParamsService = {
  typeName: TYPE_NAME,
  method: "Params",
  Request: QueryParamsRequest,
  Response: QueryParamsResponse,
} as const;

