// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file terra/market/v1beta1/tx.proto (package terra.market.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgSwap, MsgSwapResponse, MsgSwapSend, MsgSwapSendResponse } from "./tx_pb.js";

const TYPE_NAME = "terra.market.v1beta1.Msg";

/**
 * Swap defines a method for swapping coin from one denom to another
 * denom.
 *
 * @generated from rpc terra.market.v1beta1.Msg.Swap
 */
export const MsgSwapService = {
  typeName: TYPE_NAME,
  method: "Swap",
  Request: MsgSwap,
  Response: MsgSwapResponse,
} as const;

/**
 * SwapSend defines a method for swapping and sending coin from a account to other
 * account.
 *
 * @generated from rpc terra.market.v1beta1.Msg.SwapSend
 */
export const MsgSwapSendService = {
  typeName: TYPE_NAME,
  method: "SwapSend",
  Request: MsgSwapSend,
  Response: MsgSwapSendResponse,
} as const;

