// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file vsc/redeem/v1/query.proto (package vsc.redeem.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryInfoRequest, QueryInfoResponse, QueryParamsRequest, QueryParamsResponse } from "./query_pb.js";

const TYPE_NAME = "vsc.redeem.v1.Query";

/**
 * Params queries all parameters of the ibc-transfer module.
 *
 * @generated from rpc vsc.redeem.v1.Query.Params
 */
export const QueryParamsService = {
  typeName: TYPE_NAME,
  method: "Params",
  Request: QueryParamsRequest,
  Response: QueryParamsResponse,
} as const;

/**
 * @generated from rpc vsc.redeem.v1.Query.Info
 */
export const QueryInfoService = {
  typeName: TYPE_NAME,
  method: "Info",
  Request: QueryInfoRequest,
  Response: QueryInfoResponse,
} as const;

