// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file vsc/reward/v1/reward.proto (package vsc.reward.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * Params defines the module parameters for the x/oracle module.
 *
 * @generated from message vsc.reward.v1.Params
 */
export class Params extends Message<Params> {
  /**
   * TargetRewardPerDay defines the target reward per day per validators to
   * receive
   *
   * @generated from field: string target_rewards_per_day = 1;
   */
  targetRewardsPerDay = "";

  /**
   * MaxRewardsPerDay defines the maximum rewards per day per validators to
   * receive
   *
   * @generated from field: string max_rewards_per_day = 2;
   */
  maxRewardsPerDay = "";

  /**
   * MaxBalanceDepletion defines the maximum balance depletion percentage from
   * the balancing pool for all validators to receive overall
   *
   * @generated from field: string max_balance_depletion = 3;
   */
  maxBalanceDepletion = "";

  constructor(data?: PartialMessage<Params>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "vsc.reward.v1.Params";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "target_rewards_per_day", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "max_rewards_per_day", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "max_balance_depletion", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Params {
    return new Params().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Params {
    return new Params().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Params {
    return new Params().fromJsonString(jsonString, options);
  }

  static equals(a: Params | PlainMessage<Params> | undefined, b: Params | PlainMessage<Params> | undefined): boolean {
    return proto3.util.equals(Params, a, b);
  }
}

