// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file cosmwasm/wasm/v1/query.proto (package cosmwasm.wasm.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryContractInfoRequest, QueryContractInfoResponse } from "./query_pb.js";

const TYPE_NAME = "cosmwasm.wasm.v1.Query";

/**
 * ContractInfo gets the contract meta data
 *
 * @generated from rpc cosmwasm.wasm.v1.Query.ContractInfo
 */
export const QueryContractInfoService = {
  typeName: TYPE_NAME,
  method: "ContractInfo",
  Request: QueryContractInfoRequest,
  Response: QueryContractInfoResponse,
} as const;

