// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file ibc/lightclients/attestations/v1/attestations.proto (package ibc.lightclients.attestations.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * ClientState defines an attestor-based light client that tracks the current
 * consensus state and if the client is frozen.
 *
 * @generated from message ibc.lightclients.attestations.v1.ClientState
 */
export class ClientState extends Message<ClientState> {
  /**
   * trusted attestor set (EOA addresses)
   *
   * @generated from field: repeated string attestor_addresses = 1;
   */
  attestorAddresses: string[] = [];

  /**
   * quorum threshold (minimum number of unique attestor signatures required)
   *
   * @generated from field: uint32 min_required_sigs = 2;
   */
  minRequiredSigs = 0;

  /**
   * highest height that has been trusted
   *
   * @generated from field: uint64 latest_height = 3;
   */
  latestHeight = protoInt64.zero;

  /**
   * when true, all verification and updates MUST fail
   *
   * @generated from field: bool is_frozen = 4;
   */
  isFrozen = false;

  constructor(data?: PartialMessage<ClientState>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ibc.lightclients.attestations.v1.ClientState";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "attestor_addresses", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "min_required_sigs", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "latest_height", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "is_frozen", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClientState {
    return new ClientState().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClientState {
    return new ClientState().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClientState {
    return new ClientState().fromJsonString(jsonString, options);
  }

  static equals(a: ClientState | PlainMessage<ClientState> | undefined, b: ClientState | PlainMessage<ClientState> | undefined): boolean {
    return proto3.util.equals(ClientState, a, b);
  }
}

/**
 * ConsensusState defines an attestor consensus state. The timestamp of a
 * consensus state is stored per height.
 *
 * @generated from message ibc.lightclients.attestations.v1.ConsensusState
 */
export class ConsensusState extends Message<ConsensusState> {
  /**
   * trusted UNIX timestamp (nanoseconds) for the height
   *
   * @generated from field: uint64 timestamp = 1;
   */
  timestamp = protoInt64.zero;

  constructor(data?: PartialMessage<ConsensusState>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ibc.lightclients.attestations.v1.ConsensusState";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "timestamp", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ConsensusState {
    return new ConsensusState().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ConsensusState {
    return new ConsensusState().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ConsensusState {
    return new ConsensusState().fromJsonString(jsonString, options);
  }

  static equals(a: ConsensusState | PlainMessage<ConsensusState> | undefined, b: ConsensusState | PlainMessage<ConsensusState> | undefined): boolean {
    return proto3.util.equals(ConsensusState, a, b);
  }
}

/**
 * AttestationProof is used for client updates and membership verification.
 * All attestor signatures cover sha256(attestationData).
 *
 * @generated from message ibc.lightclients.attestations.v1.AttestationProof
 */
export class AttestationProof extends Message<AttestationProof> {
  /**
   * the attestation data that was signed (ABI-encoded StateAttestation or PacketAttestation)
   *
   * @generated from field: bytes attestation_data = 1;
   */
  attestationData = new Uint8Array(0);

  /**
   * array of 65-byte ECDSA signatures (r||s||v)
   *
   * @generated from field: repeated bytes signatures = 2;
   */
  signatures: Uint8Array[] = [];

  constructor(data?: PartialMessage<AttestationProof>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ibc.lightclients.attestations.v1.AttestationProof";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "attestation_data", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 2, name: "signatures", kind: "scalar", T: 12 /* ScalarType.BYTES */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AttestationProof {
    return new AttestationProof().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AttestationProof {
    return new AttestationProof().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AttestationProof {
    return new AttestationProof().fromJsonString(jsonString, options);
  }

  static equals(a: AttestationProof | PlainMessage<AttestationProof> | undefined, b: AttestationProof | PlainMessage<AttestationProof> | undefined): boolean {
    return proto3.util.equals(AttestationProof, a, b);
  }
}

