// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file vsc/reward/v1/tx.proto (package vsc.reward.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgEditRewardParams, MsgEditRewardParamsResponse } from "./tx_pb.js";

const TYPE_NAME = "vsc.reward.v1.Msg";

/**
 * Dummy comment to avoid reformatting
 *
 * @generated from rpc vsc.reward.v1.Msg.EditRewardParams
 */
export const MsgEditRewardParamsService = {
  typeName: TYPE_NAME,
  method: "EditRewardParams",
  Request: MsgEditRewardParams,
  Response: MsgEditRewardParamsResponse,
} as const;

