// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file terra/taxexemption/v1/genesis.proto (package terra.taxexemption.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Zone } from "cosmes/protobufs/sdk53/terra/taxexemption/v1/taxexemption_pb.js";

/**
 * GenesisState defines the taxexemption module's genesis state.
 *
 * @generated from message terra.taxexemption.v1.GenesisState
 */
export class GenesisState extends Message<GenesisState> {
  /**
   * @generated from field: repeated terra.taxexemption.v1.Zone zone_list = 1;
   */
  zoneList: Zone[] = [];

  /**
   * @generated from field: repeated terra.taxexemption.v1.AddressesByZone addresses_by_zone = 2;
   */
  addressesByZone: AddressesByZone[] = [];

  constructor(data?: PartialMessage<GenesisState>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.taxexemption.v1.GenesisState";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "zone_list", kind: "message", T: Zone, repeated: true },
    { no: 2, name: "addresses_by_zone", kind: "message", T: AddressesByZone, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GenesisState {
    return new GenesisState().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GenesisState {
    return new GenesisState().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GenesisState {
    return new GenesisState().fromJsonString(jsonString, options);
  }

  static equals(a: GenesisState | PlainMessage<GenesisState> | undefined, b: GenesisState | PlainMessage<GenesisState> | undefined): boolean {
    return proto3.util.equals(GenesisState, a, b);
  }
}

/**
 * @generated from message terra.taxexemption.v1.AddressesByZone
 */
export class AddressesByZone extends Message<AddressesByZone> {
  /**
   * @generated from field: string zone = 1;
   */
  zone = "";

  /**
   * @generated from field: repeated string addresses = 2;
   */
  addresses: string[] = [];

  constructor(data?: PartialMessage<AddressesByZone>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.taxexemption.v1.AddressesByZone";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "zone", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "addresses", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AddressesByZone {
    return new AddressesByZone().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AddressesByZone {
    return new AddressesByZone().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AddressesByZone {
    return new AddressesByZone().fromJsonString(jsonString, options);
  }

  static equals(a: AddressesByZone | PlainMessage<AddressesByZone> | undefined, b: AddressesByZone | PlainMessage<AddressesByZone> | undefined): boolean {
    return proto3.util.equals(AddressesByZone, a, b);
  }
}

