// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file terra/taxexemption/v1/query.proto (package terra.taxexemption.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { PageRequest, PageResponse } from "cosmes/protobufs/sdk53/cosmos/base/query/v1beta1/pagination_pb.js";
import { Zone } from "cosmes/protobufs/sdk53/terra/taxexemption/v1/taxexemption_pb.js";

/**
 * @generated from message terra.taxexemption.v1.QueryTaxableRequest
 */
export class QueryTaxableRequest extends Message<QueryTaxableRequest> {
  /**
   * @generated from field: string from_address = 1;
   */
  fromAddress = "";

  /**
   * @generated from field: string to_address = 2;
   */
  toAddress = "";

  constructor(data?: PartialMessage<QueryTaxableRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.taxexemption.v1.QueryTaxableRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "from_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "to_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryTaxableRequest {
    return new QueryTaxableRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryTaxableRequest {
    return new QueryTaxableRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryTaxableRequest {
    return new QueryTaxableRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryTaxableRequest | PlainMessage<QueryTaxableRequest> | undefined, b: QueryTaxableRequest | PlainMessage<QueryTaxableRequest> | undefined): boolean {
    return proto3.util.equals(QueryTaxableRequest, a, b);
  }
}

/**
 * @generated from message terra.taxexemption.v1.QueryTaxableResponse
 */
export class QueryTaxableResponse extends Message<QueryTaxableResponse> {
  /**
   * @generated from field: bool taxable = 1;
   */
  taxable = false;

  constructor(data?: PartialMessage<QueryTaxableResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.taxexemption.v1.QueryTaxableResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "taxable", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryTaxableResponse {
    return new QueryTaxableResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryTaxableResponse {
    return new QueryTaxableResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryTaxableResponse {
    return new QueryTaxableResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryTaxableResponse | PlainMessage<QueryTaxableResponse> | undefined, b: QueryTaxableResponse | PlainMessage<QueryTaxableResponse> | undefined): boolean {
    return proto3.util.equals(QueryTaxableResponse, a, b);
  }
}

/**
 * @generated from message terra.taxexemption.v1.QueryTaxExemptionZonesRequest
 */
export class QueryTaxExemptionZonesRequest extends Message<QueryTaxExemptionZonesRequest> {
  /**
   * @generated from field: cosmos.base.query.v1beta1.PageRequest pagination = 2;
   */
  pagination?: PageRequest;

  constructor(data?: PartialMessage<QueryTaxExemptionZonesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.taxexemption.v1.QueryTaxExemptionZonesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "pagination", kind: "message", T: PageRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryTaxExemptionZonesRequest {
    return new QueryTaxExemptionZonesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryTaxExemptionZonesRequest {
    return new QueryTaxExemptionZonesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryTaxExemptionZonesRequest {
    return new QueryTaxExemptionZonesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryTaxExemptionZonesRequest | PlainMessage<QueryTaxExemptionZonesRequest> | undefined, b: QueryTaxExemptionZonesRequest | PlainMessage<QueryTaxExemptionZonesRequest> | undefined): boolean {
    return proto3.util.equals(QueryTaxExemptionZonesRequest, a, b);
  }
}

/**
 * @generated from message terra.taxexemption.v1.QueryTaxExemptionZonesResponse
 */
export class QueryTaxExemptionZonesResponse extends Message<QueryTaxExemptionZonesResponse> {
  /**
   * @generated from field: repeated terra.taxexemption.v1.Zone zones = 1;
   */
  zones: Zone[] = [];

  /**
   * @generated from field: cosmos.base.query.v1beta1.PageResponse pagination = 2;
   */
  pagination?: PageResponse;

  constructor(data?: PartialMessage<QueryTaxExemptionZonesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.taxexemption.v1.QueryTaxExemptionZonesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "zones", kind: "message", T: Zone, repeated: true },
    { no: 2, name: "pagination", kind: "message", T: PageResponse },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryTaxExemptionZonesResponse {
    return new QueryTaxExemptionZonesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryTaxExemptionZonesResponse {
    return new QueryTaxExemptionZonesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryTaxExemptionZonesResponse {
    return new QueryTaxExemptionZonesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryTaxExemptionZonesResponse | PlainMessage<QueryTaxExemptionZonesResponse> | undefined, b: QueryTaxExemptionZonesResponse | PlainMessage<QueryTaxExemptionZonesResponse> | undefined): boolean {
    return proto3.util.equals(QueryTaxExemptionZonesResponse, a, b);
  }
}

/**
 * @generated from message terra.taxexemption.v1.QueryTaxExemptionAddressRequest
 */
export class QueryTaxExemptionAddressRequest extends Message<QueryTaxExemptionAddressRequest> {
  /**
   * @generated from field: string zone_name = 1;
   */
  zoneName = "";

  /**
   * @generated from field: cosmos.base.query.v1beta1.PageRequest pagination = 2;
   */
  pagination?: PageRequest;

  constructor(data?: PartialMessage<QueryTaxExemptionAddressRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.taxexemption.v1.QueryTaxExemptionAddressRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "zone_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "pagination", kind: "message", T: PageRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryTaxExemptionAddressRequest {
    return new QueryTaxExemptionAddressRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryTaxExemptionAddressRequest {
    return new QueryTaxExemptionAddressRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryTaxExemptionAddressRequest {
    return new QueryTaxExemptionAddressRequest().fromJsonString(jsonString, options);
  }

  static equals(a: QueryTaxExemptionAddressRequest | PlainMessage<QueryTaxExemptionAddressRequest> | undefined, b: QueryTaxExemptionAddressRequest | PlainMessage<QueryTaxExemptionAddressRequest> | undefined): boolean {
    return proto3.util.equals(QueryTaxExemptionAddressRequest, a, b);
  }
}

/**
 * @generated from message terra.taxexemption.v1.QueryTaxExemptionAddressResponse
 */
export class QueryTaxExemptionAddressResponse extends Message<QueryTaxExemptionAddressResponse> {
  /**
   * @generated from field: repeated string addresses = 1;
   */
  addresses: string[] = [];

  /**
   * @generated from field: cosmos.base.query.v1beta1.PageResponse pagination = 2;
   */
  pagination?: PageResponse;

  constructor(data?: PartialMessage<QueryTaxExemptionAddressResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.taxexemption.v1.QueryTaxExemptionAddressResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "addresses", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "pagination", kind: "message", T: PageResponse },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryTaxExemptionAddressResponse {
    return new QueryTaxExemptionAddressResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryTaxExemptionAddressResponse {
    return new QueryTaxExemptionAddressResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryTaxExemptionAddressResponse {
    return new QueryTaxExemptionAddressResponse().fromJsonString(jsonString, options);
  }

  static equals(a: QueryTaxExemptionAddressResponse | PlainMessage<QueryTaxExemptionAddressResponse> | undefined, b: QueryTaxExemptionAddressResponse | PlainMessage<QueryTaxExemptionAddressResponse> | undefined): boolean {
    return proto3.util.equals(QueryTaxExemptionAddressResponse, a, b);
  }
}

