// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file terra/taxexemption/v1/query.proto (package terra.taxexemption.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryTaxableRequest, QueryTaxableResponse, QueryTaxExemptionAddressRequest, QueryTaxExemptionAddressResponse, QueryTaxExemptionZonesRequest, QueryTaxExemptionZonesResponse } from "./query_pb.js";

const TYPE_NAME = "terra.taxexemption.v1.Query";

/**
 * @generated from rpc terra.taxexemption.v1.Query.Taxable
 */
export const QueryTaxableService = {
  typeName: TYPE_NAME,
  method: "Taxable",
  Request: QueryTaxableRequest,
  Response: QueryTaxableResponse,
} as const;

/**
 * @generated from rpc terra.taxexemption.v1.Query.TaxExemptionZonesList
 */
export const QueryTaxExemptionZonesListService = {
  typeName: TYPE_NAME,
  method: "TaxExemptionZonesList",
  Request: QueryTaxExemptionZonesRequest,
  Response: QueryTaxExemptionZonesResponse,
} as const;

/**
 * @generated from rpc terra.taxexemption.v1.Query.TaxExemptionAddressList
 */
export const QueryTaxExemptionAddressListService = {
  typeName: TYPE_NAME,
  method: "TaxExemptionAddressList",
  Request: QueryTaxExemptionAddressRequest,
  Response: QueryTaxExemptionAddressResponse,
} as const;

