// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file terra/taxexemption/v1/tx.proto (package terra.taxexemption.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * MsgAddTaxExemptionZone defines a message for adding a tax exemption zone.
 *
 * @generated from message terra.taxexemption.v1.MsgAddTaxExemptionZone
 */
export class MsgAddTaxExemptionZone extends Message<MsgAddTaxExemptionZone> {
  /**
   * @generated from field: string zone = 1;
   */
  zone = "";

  /**
   * @generated from field: bool outgoing = 2;
   */
  outgoing = false;

  /**
   * @generated from field: bool incoming = 3;
   */
  incoming = false;

  /**
   * @generated from field: bool cross_zone = 4;
   */
  crossZone = false;

  /**
   * @generated from field: repeated string addresses = 5;
   */
  addresses: string[] = [];

  /**
   * @generated from field: string authority = 6;
   */
  authority = "";

  constructor(data?: PartialMessage<MsgAddTaxExemptionZone>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.taxexemption.v1.MsgAddTaxExemptionZone";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "zone", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "outgoing", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "incoming", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "cross_zone", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "addresses", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 6, name: "authority", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgAddTaxExemptionZone {
    return new MsgAddTaxExemptionZone().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgAddTaxExemptionZone {
    return new MsgAddTaxExemptionZone().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgAddTaxExemptionZone {
    return new MsgAddTaxExemptionZone().fromJsonString(jsonString, options);
  }

  static equals(a: MsgAddTaxExemptionZone | PlainMessage<MsgAddTaxExemptionZone> | undefined, b: MsgAddTaxExemptionZone | PlainMessage<MsgAddTaxExemptionZone> | undefined): boolean {
    return proto3.util.equals(MsgAddTaxExemptionZone, a, b);
  }
}

/**
 * @generated from message terra.taxexemption.v1.MsgAddTaxExemptionZoneResponse
 */
export class MsgAddTaxExemptionZoneResponse extends Message<MsgAddTaxExemptionZoneResponse> {
  constructor(data?: PartialMessage<MsgAddTaxExemptionZoneResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.taxexemption.v1.MsgAddTaxExemptionZoneResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgAddTaxExemptionZoneResponse {
    return new MsgAddTaxExemptionZoneResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgAddTaxExemptionZoneResponse {
    return new MsgAddTaxExemptionZoneResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgAddTaxExemptionZoneResponse {
    return new MsgAddTaxExemptionZoneResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgAddTaxExemptionZoneResponse | PlainMessage<MsgAddTaxExemptionZoneResponse> | undefined, b: MsgAddTaxExemptionZoneResponse | PlainMessage<MsgAddTaxExemptionZoneResponse> | undefined): boolean {
    return proto3.util.equals(MsgAddTaxExemptionZoneResponse, a, b);
  }
}

/**
 * MsgRemoveTaxExemptionZone defines a message for removing a tax exemption zone.
 *
 * @generated from message terra.taxexemption.v1.MsgRemoveTaxExemptionZone
 */
export class MsgRemoveTaxExemptionZone extends Message<MsgRemoveTaxExemptionZone> {
  /**
   * @generated from field: string zone = 1;
   */
  zone = "";

  /**
   * @generated from field: string authority = 2;
   */
  authority = "";

  constructor(data?: PartialMessage<MsgRemoveTaxExemptionZone>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.taxexemption.v1.MsgRemoveTaxExemptionZone";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "zone", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "authority", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgRemoveTaxExemptionZone {
    return new MsgRemoveTaxExemptionZone().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgRemoveTaxExemptionZone {
    return new MsgRemoveTaxExemptionZone().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgRemoveTaxExemptionZone {
    return new MsgRemoveTaxExemptionZone().fromJsonString(jsonString, options);
  }

  static equals(a: MsgRemoveTaxExemptionZone | PlainMessage<MsgRemoveTaxExemptionZone> | undefined, b: MsgRemoveTaxExemptionZone | PlainMessage<MsgRemoveTaxExemptionZone> | undefined): boolean {
    return proto3.util.equals(MsgRemoveTaxExemptionZone, a, b);
  }
}

/**
 * @generated from message terra.taxexemption.v1.MsgRemoveTaxExemptionZoneResponse
 */
export class MsgRemoveTaxExemptionZoneResponse extends Message<MsgRemoveTaxExemptionZoneResponse> {
  constructor(data?: PartialMessage<MsgRemoveTaxExemptionZoneResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.taxexemption.v1.MsgRemoveTaxExemptionZoneResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgRemoveTaxExemptionZoneResponse {
    return new MsgRemoveTaxExemptionZoneResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgRemoveTaxExemptionZoneResponse {
    return new MsgRemoveTaxExemptionZoneResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgRemoveTaxExemptionZoneResponse {
    return new MsgRemoveTaxExemptionZoneResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgRemoveTaxExemptionZoneResponse | PlainMessage<MsgRemoveTaxExemptionZoneResponse> | undefined, b: MsgRemoveTaxExemptionZoneResponse | PlainMessage<MsgRemoveTaxExemptionZoneResponse> | undefined): boolean {
    return proto3.util.equals(MsgRemoveTaxExemptionZoneResponse, a, b);
  }
}

/**
 * MsgModifyTaxExemptionZone defines a message for modifying a tax exemption zone.
 *
 * @generated from message terra.taxexemption.v1.MsgModifyTaxExemptionZone
 */
export class MsgModifyTaxExemptionZone extends Message<MsgModifyTaxExemptionZone> {
  /**
   * @generated from field: string zone = 1;
   */
  zone = "";

  /**
   * @generated from field: bool outgoing = 2;
   */
  outgoing = false;

  /**
   * @generated from field: bool incoming = 3;
   */
  incoming = false;

  /**
   * @generated from field: bool cross_zone = 4;
   */
  crossZone = false;

  /**
   * @generated from field: string authority = 5;
   */
  authority = "";

  constructor(data?: PartialMessage<MsgModifyTaxExemptionZone>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.taxexemption.v1.MsgModifyTaxExemptionZone";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "zone", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "outgoing", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "incoming", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "cross_zone", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "authority", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgModifyTaxExemptionZone {
    return new MsgModifyTaxExemptionZone().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgModifyTaxExemptionZone {
    return new MsgModifyTaxExemptionZone().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgModifyTaxExemptionZone {
    return new MsgModifyTaxExemptionZone().fromJsonString(jsonString, options);
  }

  static equals(a: MsgModifyTaxExemptionZone | PlainMessage<MsgModifyTaxExemptionZone> | undefined, b: MsgModifyTaxExemptionZone | PlainMessage<MsgModifyTaxExemptionZone> | undefined): boolean {
    return proto3.util.equals(MsgModifyTaxExemptionZone, a, b);
  }
}

/**
 * @generated from message terra.taxexemption.v1.MsgModifyTaxExemptionZoneResponse
 */
export class MsgModifyTaxExemptionZoneResponse extends Message<MsgModifyTaxExemptionZoneResponse> {
  constructor(data?: PartialMessage<MsgModifyTaxExemptionZoneResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.taxexemption.v1.MsgModifyTaxExemptionZoneResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgModifyTaxExemptionZoneResponse {
    return new MsgModifyTaxExemptionZoneResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgModifyTaxExemptionZoneResponse {
    return new MsgModifyTaxExemptionZoneResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgModifyTaxExemptionZoneResponse {
    return new MsgModifyTaxExemptionZoneResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgModifyTaxExemptionZoneResponse | PlainMessage<MsgModifyTaxExemptionZoneResponse> | undefined, b: MsgModifyTaxExemptionZoneResponse | PlainMessage<MsgModifyTaxExemptionZoneResponse> | undefined): boolean {
    return proto3.util.equals(MsgModifyTaxExemptionZoneResponse, a, b);
  }
}

/**
 * MsgAddTaxExemptionAddress defines a message for adding tax exemption addresses.
 *
 * @generated from message terra.taxexemption.v1.MsgAddTaxExemptionAddress
 */
export class MsgAddTaxExemptionAddress extends Message<MsgAddTaxExemptionAddress> {
  /**
   * @generated from field: string zone = 1;
   */
  zone = "";

  /**
   * @generated from field: repeated string addresses = 2;
   */
  addresses: string[] = [];

  /**
   * @generated from field: string authority = 3;
   */
  authority = "";

  constructor(data?: PartialMessage<MsgAddTaxExemptionAddress>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.taxexemption.v1.MsgAddTaxExemptionAddress";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "zone", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "addresses", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 3, name: "authority", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgAddTaxExemptionAddress {
    return new MsgAddTaxExemptionAddress().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgAddTaxExemptionAddress {
    return new MsgAddTaxExemptionAddress().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgAddTaxExemptionAddress {
    return new MsgAddTaxExemptionAddress().fromJsonString(jsonString, options);
  }

  static equals(a: MsgAddTaxExemptionAddress | PlainMessage<MsgAddTaxExemptionAddress> | undefined, b: MsgAddTaxExemptionAddress | PlainMessage<MsgAddTaxExemptionAddress> | undefined): boolean {
    return proto3.util.equals(MsgAddTaxExemptionAddress, a, b);
  }
}

/**
 * @generated from message terra.taxexemption.v1.MsgAddTaxExemptionAddressResponse
 */
export class MsgAddTaxExemptionAddressResponse extends Message<MsgAddTaxExemptionAddressResponse> {
  constructor(data?: PartialMessage<MsgAddTaxExemptionAddressResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.taxexemption.v1.MsgAddTaxExemptionAddressResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgAddTaxExemptionAddressResponse {
    return new MsgAddTaxExemptionAddressResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgAddTaxExemptionAddressResponse {
    return new MsgAddTaxExemptionAddressResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgAddTaxExemptionAddressResponse {
    return new MsgAddTaxExemptionAddressResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgAddTaxExemptionAddressResponse | PlainMessage<MsgAddTaxExemptionAddressResponse> | undefined, b: MsgAddTaxExemptionAddressResponse | PlainMessage<MsgAddTaxExemptionAddressResponse> | undefined): boolean {
    return proto3.util.equals(MsgAddTaxExemptionAddressResponse, a, b);
  }
}

/**
 * MsgRemoveTaxExemptionAddress defines a message for removing tax exemption addresses.
 *
 * @generated from message terra.taxexemption.v1.MsgRemoveTaxExemptionAddress
 */
export class MsgRemoveTaxExemptionAddress extends Message<MsgRemoveTaxExemptionAddress> {
  /**
   * @generated from field: string zone = 1;
   */
  zone = "";

  /**
   * @generated from field: repeated string addresses = 2;
   */
  addresses: string[] = [];

  /**
   * @generated from field: string authority = 3;
   */
  authority = "";

  constructor(data?: PartialMessage<MsgRemoveTaxExemptionAddress>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.taxexemption.v1.MsgRemoveTaxExemptionAddress";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "zone", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "addresses", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 3, name: "authority", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgRemoveTaxExemptionAddress {
    return new MsgRemoveTaxExemptionAddress().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgRemoveTaxExemptionAddress {
    return new MsgRemoveTaxExemptionAddress().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgRemoveTaxExemptionAddress {
    return new MsgRemoveTaxExemptionAddress().fromJsonString(jsonString, options);
  }

  static equals(a: MsgRemoveTaxExemptionAddress | PlainMessage<MsgRemoveTaxExemptionAddress> | undefined, b: MsgRemoveTaxExemptionAddress | PlainMessage<MsgRemoveTaxExemptionAddress> | undefined): boolean {
    return proto3.util.equals(MsgRemoveTaxExemptionAddress, a, b);
  }
}

/**
 * @generated from message terra.taxexemption.v1.MsgRemoveTaxExemptionAddressResponse
 */
export class MsgRemoveTaxExemptionAddressResponse extends Message<MsgRemoveTaxExemptionAddressResponse> {
  constructor(data?: PartialMessage<MsgRemoveTaxExemptionAddressResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "terra.taxexemption.v1.MsgRemoveTaxExemptionAddressResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgRemoveTaxExemptionAddressResponse {
    return new MsgRemoveTaxExemptionAddressResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgRemoveTaxExemptionAddressResponse {
    return new MsgRemoveTaxExemptionAddressResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgRemoveTaxExemptionAddressResponse {
    return new MsgRemoveTaxExemptionAddressResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgRemoveTaxExemptionAddressResponse | PlainMessage<MsgRemoveTaxExemptionAddressResponse> | undefined, b: MsgRemoveTaxExemptionAddressResponse | PlainMessage<MsgRemoveTaxExemptionAddressResponse> | undefined): boolean {
    return proto3.util.equals(MsgRemoveTaxExemptionAddressResponse, a, b);
  }
}

